## Append samples of your project ##
resources:
- v1alpha1_routetable.yaml
- v1alpha1_addresspool.yaml
- v1alpha1_externalnetwork.yaml
- v1alpha1_bgppeer.yaml
- v1alpha1_bgpadvertisement.yaml
- v1alpha1_bgpnodestate.yaml
- v1alpha1_elasticip.yaml
- v1alpha1_elasticipattachment.yaml
- v1alpha1_allocationpool.yaml
- v1alpha1_allocationclaim.yaml
- v1alpha1_allocationlease.yaml
- v1alpha1_natgateway.yaml
- v1alpha1_externalnetworkattachment.yaml
- v1alpha1_servicenatattachment.yaml
- v1alpha1_vpcpeering.yaml
- v1alpha1_transitgateway.yaml
- v1alpha1_transitgatewayroutetable.yaml
- v1alpha1_transitgatewayattachment.yaml
- v1alpha1_arpadvertisement.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
