## Append samples of your project ##
resources:
- v1alpha1_routetable.yaml
- v1alpha1_addresspool.yaml
- v1alpha1_externalnetwork.yaml
- v1alpha1_bgppeer.yaml
- v1alpha1_bgpadvertisement.yaml
- v1alpha1_bgpnodestate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
