/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	controllerapiv1alpha1 "github.com/1outres/juneau/controller/api/v1alpha1"
	versioned "github.com/1outres/juneau/controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/1outres/juneau/controller/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/1outres/juneau/controller/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetLeaseInformer provides access to a shared informer and lister for
// SubnetLeases.
type SubnetLeaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.SubnetLeaseLister
}

type subnetLeaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSubnetLeaseInformer constructs a new informer for SubnetLease type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSubnetLeaseInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSubnetLeaseInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSubnetLeaseInformer constructs a new informer for SubnetLease type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSubnetLeaseInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().SubnetLeases().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().SubnetLeases().Watch(context.TODO(), options)
			},
		},
		&controllerapiv1alpha1.SubnetLease{},
		resyncPeriod,
		indexers,
	)
}

func (f *subnetLeaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSubnetLeaseInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *subnetLeaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&controllerapiv1alpha1.SubnetLease{}, f.defaultInformer)
}

func (f *subnetLeaseInformer) Lister() apiv1alpha1.SubnetLeaseLister {
	return apiv1alpha1.NewSubnetLeaseLister(f.Informer().GetIndexer())
}
