# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/juneau.loutres.me_vpcs.yaml
- bases/juneau.loutres.me_subnets.yaml
- bases/juneau.loutres.me_networkinterfaces.yaml
- bases/juneau.loutres.me_networkendpoints.yaml
- bases/juneau.loutres.me_routetables.yaml
- bases/juneau.loutres.me_addresspools.yaml
- bases/juneau.loutres.me_externalnetworks.yaml
- bases/juneau.loutres.me_bgppeers.yaml
- bases/juneau.loutres.me_bgpadvertisements.yaml
- bases/juneau.loutres.me_bgpnodestates.yaml
- bases/juneau.loutres.me_elasticips.yaml
- bases/juneau.loutres.me_elasticipattachments.yaml
- bases/juneau.loutres.me_allocationpools.yaml
- bases/juneau.loutres.me_allocationclaims.yaml
- bases/juneau.loutres.me_allocationleases.yaml
- bases/juneau.loutres.me_natgateways.yaml
- bases/juneau.loutres.me_externalnetworkattachments.yaml
- bases/juneau.loutres.me_servicenatattachments.yaml
- bases/juneau.loutres.me_securitygroups.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
