run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  staticcheck:
    checks:
      - all
      - -SA1019

issues:
  exclude-use-default: false
