site_name: Juneau
site_url: https://1outres.github.io/juneau/
repo_url: https://github.com/1outres/juneau
repo_name: 1outres/juneau
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      accent: green

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Resources:
    - VPC: resources/vpc.md
    - Subnet: resources/subnet.md
    - NetworkInterface: resources/networkinterface.md
  - API Reference: api-reference/v1alpha1.md
