/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/1outres/juneau/controller/api/v1alpha1"
	scheme "github.com/1outres/juneau/controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetLeasesGetter has a method to return a SubnetLeaseInterface.
// A group's client should implement this interface.
type SubnetLeasesGetter interface {
	SubnetLeases() SubnetLeaseInterface
}

// SubnetLeaseInterface has methods to work with SubnetLease resources.
type SubnetLeaseInterface interface {
	Create(ctx context.Context, subnetLease *apiv1alpha1.SubnetLease, opts v1.CreateOptions) (*apiv1alpha1.SubnetLease, error)
	Update(ctx context.Context, subnetLease *apiv1alpha1.SubnetLease, opts v1.UpdateOptions) (*apiv1alpha1.SubnetLease, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnetLease *apiv1alpha1.SubnetLease, opts v1.UpdateOptions) (*apiv1alpha1.SubnetLease, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.SubnetLease, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.SubnetLeaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.SubnetLease, err error)
	SubnetLeaseExpansion
}

// subnetLeases implements SubnetLeaseInterface
type subnetLeases struct {
	*gentype.ClientWithList[*apiv1alpha1.SubnetLease, *apiv1alpha1.SubnetLeaseList]
}

// newSubnetLeases returns a SubnetLeases
func newSubnetLeases(c *ApiV1alpha1Client) *subnetLeases {
	return &subnetLeases{
		gentype.NewClientWithList[*apiv1alpha1.SubnetLease, *apiv1alpha1.SubnetLeaseList](
			"subnetleases",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.SubnetLease { return &apiv1alpha1.SubnetLease{} },
			func() *apiv1alpha1.SubnetLeaseList { return &apiv1alpha1.SubnetLeaseList{} },
		),
	}
}
