/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/1outres/juneau/controller/api/v1alpha1"
	scheme "github.com/1outres/juneau/controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VpcsGetter has a method to return a VpcInterface.
// A group's client should implement this interface.
type VpcsGetter interface {
	Vpcs() VpcInterface
}

// VpcInterface has methods to work with Vpc resources.
type VpcInterface interface {
	Create(ctx context.Context, vpc *apiv1alpha1.Vpc, opts v1.CreateOptions) (*apiv1alpha1.Vpc, error)
	Update(ctx context.Context, vpc *apiv1alpha1.Vpc, opts v1.UpdateOptions) (*apiv1alpha1.Vpc, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vpc *apiv1alpha1.Vpc, opts v1.UpdateOptions) (*apiv1alpha1.Vpc, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Vpc, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.VpcList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Vpc, err error)
	VpcExpansion
}

// vpcs implements VpcInterface
type vpcs struct {
	*gentype.ClientWithList[*apiv1alpha1.Vpc, *apiv1alpha1.VpcList]
}

// newVpcs returns a Vpcs
func newVpcs(c *ApiV1alpha1Client) *vpcs {
	return &vpcs{
		gentype.NewClientWithList[*apiv1alpha1.Vpc, *apiv1alpha1.VpcList](
			"vpcs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.Vpc { return &apiv1alpha1.Vpc{} },
			func() *apiv1alpha1.VpcList { return &apiv1alpha1.VpcList{} },
		),
	}
}
