// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadHostEgress returns the embedded CollectionSpec for HostEgress.
func LoadHostEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HostEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load HostEgress: %w", err)
	}

	return spec, err
}

// LoadHostEgressObjects loads HostEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*HostEgressObjects
//	*HostEgressPrograms
//	*HostEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadHostEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadHostEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// HostEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressSpecs struct {
	HostEgressProgramSpecs
	HostEgressMapSpecs
	HostEgressVariableSpecs
}

// HostEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressProgramSpecs struct {
	TcPodEgress *ebpf.ProgramSpec `ebpf:"tc_pod_egress"`
}

// HostEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressMapSpecs struct {
}

// HostEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressVariableSpecs struct {
}

// HostEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressObjects struct {
	HostEgressPrograms
	HostEgressMaps
	HostEgressVariables
}

func (o *HostEgressObjects) Close() error {
	return _HostEgressClose(
		&o.HostEgressPrograms,
		&o.HostEgressMaps,
	)
}

// HostEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressMaps struct {
}

func (m *HostEgressMaps) Close() error {
	return _HostEgressClose()
}

// HostEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressVariables struct {
}

// HostEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressPrograms struct {
	TcPodEgress *ebpf.Program `ebpf:"tc_pod_egress"`
}

func (p *HostEgressPrograms) Close() error {
	return _HostEgressClose(
		p.TcPodEgress,
	)
}

func _HostEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hostegress_bpfel.o
var _HostEgressBytes []byte
