// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type HostEgressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type HostEgressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type HostEgressBgpAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type HostEgressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type HostEgressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type HostEgressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type HostEgressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type HostEgressHostIfaceVal struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	_       [2]byte
}

type HostEgressIfindexHostMacKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type HostEgressIfindexHostMacVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type HostEgressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type HostEgressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
}

type HostEgressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type HostEgressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type HostEgressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type HostEgressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
}

// LoadHostEgress returns the embedded CollectionSpec for HostEgress.
func LoadHostEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HostEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load HostEgress: %w", err)
	}

	return spec, err
}

// LoadHostEgressObjects loads HostEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*HostEgressObjects
//	*HostEgressPrograms
//	*HostEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadHostEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadHostEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// HostEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressSpecs struct {
	HostEgressProgramSpecs
	HostEgressMapSpecs
	HostEgressVariableSpecs
}

// HostEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressProgramSpecs struct {
	TcHostEgress *ebpf.ProgramSpec `ebpf:"tc_host_egress"`
}

// HostEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressMapSpecs struct {
	ArpTable        *ebpf.MapSpec `ebpf:"arp_table"`
	BgpAddressPools *ebpf.MapSpec `ebpf:"bgp_address_pools"`
	Fdb             *ebpf.MapSpec `ebpf:"fdb"`
	FibInner        *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap          *ebpf.MapSpec `ebpf:"fib_map"`
	HostIface       *ebpf.MapSpec `ebpf:"host_iface"`
	IfindexHostMac  *ebpf.MapSpec `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	NatDnatMap      *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.MapSpec `ebpf:"nat_snat_map"`
	SubnetMap       *ebpf.MapSpec `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// HostEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HostEgressVariableSpecs struct {
}

// HostEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressObjects struct {
	HostEgressPrograms
	HostEgressMaps
	HostEgressVariables
}

func (o *HostEgressObjects) Close() error {
	return _HostEgressClose(
		&o.HostEgressPrograms,
		&o.HostEgressMaps,
	)
}

// HostEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressMaps struct {
	ArpTable        *ebpf.Map `ebpf:"arp_table"`
	BgpAddressPools *ebpf.Map `ebpf:"bgp_address_pools"`
	Fdb             *ebpf.Map `ebpf:"fdb"`
	FibInner        *ebpf.Map `ebpf:"fib_inner"`
	FibMap          *ebpf.Map `ebpf:"fib_map"`
	HostIface       *ebpf.Map `ebpf:"host_iface"`
	IfindexHostMac  *ebpf.Map `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.Map `ebpf:"ifindex_subnet"`
	NatDnatMap      *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.Map `ebpf:"nat_snat_map"`
	SubnetMap       *ebpf.Map `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *HostEgressMaps) Close() error {
	return _HostEgressClose(
		m.ArpTable,
		m.BgpAddressPools,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostIface,
		m.IfindexHostMac,
		m.IfindexSubnet,
		m.NatDnatMap,
		m.NatSnatMap,
		m.SubnetMap,
		m.VxlanIfindex,
	)
}

// HostEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressVariables struct {
}

// HostEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadHostEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type HostEgressPrograms struct {
	TcHostEgress *ebpf.Program `ebpf:"tc_host_egress"`
}

func (p *HostEgressPrograms) Close() error {
	return _HostEgressClose(
		p.TcHostEgress,
	)
}

func _HostEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hostegress_bpfeb.o
var _HostEgressBytes []byte
