// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type L2IngressAclMetaVal struct {
	_               structs.HostLayout
	IngressCount    uint32
	EgressCount     uint32
	RulesetVersion  uint64
	HasIngressRules uint8
	HasEgressRules  uint8
	Pad             [6]uint8
}

type L2IngressAclRule struct {
	_         structs.HostLayout
	Proto     uint16
	PortLo    uint16
	PortHi    uint16
	Priority  uint16
	PeerV4    uint32
	Direction uint8
	Prefixlen uint8
	Verdict   uint8
	Pad       uint8
}

type L2IngressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type L2IngressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type L2IngressBackendKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
	Index     uint32
}

type L2IngressBackendVal struct {
	_               structs.HostLayout
	BackendIp       uint32
	BackendPort     uint16
	Kind            uint8
	Pad             uint8
	BackendSubnetId uint32
}

type L2IngressCtKey struct {
	_     structs.HostLayout
	Scope uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type L2IngressCtVal struct {
	_            structs.HostLayout
	NewSaddr     uint32
	NewDaddr     uint32
	NewSport     uint16
	NewDport     uint16
	NextSubnetId uint32
	Action       uint8
	State        uint8
	FlagsSeen    uint8
	Pad          uint8
	_            [4]byte
	LastSeenNs   uint64
}

type L2IngressExternalAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type L2IngressExternalArpKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Ipaddr  uint32
}

type L2IngressExternalArpVal struct {
	_   structs.HostLayout
	Mac [6]uint8
	Pad [2]uint8
}

type L2IngressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type L2IngressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type L2IngressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type L2IngressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type L2IngressIfindexHostMacKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type L2IngressIfindexHostMacVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type L2IngressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type L2IngressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipv4     uint32
}

type L2IngressIpv4FragKey struct {
	_     structs.HostLayout
	VpcId uint32
	Saddr uint32
	Daddr uint32
	Id    uint16
	Proto uint8
	Pad   uint8
}

type L2IngressIpv4FragVal struct {
	_          structs.HostLayout
	Sport      uint16
	Dport      uint16
	_          [4]byte
	LastSeenNs uint64
}

type L2IngressL2ArpKey struct {
	_    structs.HostLayout
	Ipv4 uint32
}

type L2IngressL2ArpVal struct {
	_   structs.HostLayout
	Mac [6]uint8
	Pad [2]uint8
}

type L2IngressL2FdbKey struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type L2IngressL2FdbVal struct {
	_          structs.HostLayout
	Ifindex    uint32
	VtepIp     uint32
	LastSeenNs uint64
	Flags      uint32
	Pad        uint32
}

type L2IngressL2GatewayKey struct {
	_   structs.HostLayout
	Vni uint32
}

type L2IngressL2GatewayVal struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	Pad     [2]uint8
}

type L2IngressL2IfindexKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type L2IngressL2IfindexVal struct {
	_   structs.HostLayout
	Vni uint32
}

type L2IngressL2NetworkKey struct {
	_   structs.HostLayout
	Vni uint32
}

type L2IngressL2NetworkVal struct {
	_     structs.HostLayout
	VpcId uint32
}

type L2IngressLbBackendKey struct {
	_     structs.HostLayout
	Vip   uint32
	Port  uint16
	Proto uint8
	Pad   uint8
	Index uint32
}

type L2IngressLbBackendVal struct {
	_               structs.HostLayout
	BackendIp       uint32
	BackendPort     uint16
	Pad             [2]uint8
	BackendSubnetId uint32
}

type L2IngressLbServiceKey struct {
	_     structs.HostLayout
	Vip   uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type L2IngressLbServiceVal struct {
	_            structs.HostLayout
	BackendCount uint32
	Gen          uint32
	Flags        uint32
	Pad          uint32
}

type L2IngressNaptSrcKey struct {
	_            structs.HostLayout
	NatGatewayId uint32
}

type L2IngressNaptSrcVal struct {
	_      structs.HostLayout
	HostIp uint32
}

type L2IngressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type L2IngressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type L2IngressPolicyCtKey struct {
	_     structs.HostLayout
	Epoch uint32
	Scope uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Hook  uint8
	Pad   [2]uint8
}

type L2IngressPolicyCtVal struct {
	_          structs.HostLayout
	State      uint8
	FlagsSeen  uint8
	Pad        [2]uint8
	_          [4]byte
	LastSeenNs uint64
}

type L2IngressServiceAclKey struct {
	_           structs.HostLayout
	ClusterIp   uint32
	Port        uint16
	Proto       uint8
	Pad         uint8
	CallerVpcId uint32
}

type L2IngressServiceAffinityKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
	ClientIp  uint32
}

type L2IngressServiceAffinityVal struct {
	_            structs.HostLayout
	BackendIndex uint32
	BackendGen   uint32
	ExpiresAtNs  uint64
}

type L2IngressServiceKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
}

type L2IngressServiceVal struct {
	_            structs.HostLayout
	OwnerVpcId   uint32
	BackendCount uint32
	AffinitySec  uint32
	Flags        uint32
	Gen          uint32
}

type L2IngressSgMembershipKey struct {
	_     structs.HostLayout
	VpcId uint32
	Ipv4  uint32
}

type L2IngressSgMembershipVal struct {
	_     structs.HostLayout
	Count uint8
	Pad   [3]uint8
	Sgs   [2]uint32
}

type L2IngressSgMetaVal struct {
	_              structs.HostLayout
	IngressCount   uint32
	EgressCount    uint32
	RulesetVersion uint32
	HasEgressRules uint8
	Pad            [3]uint8
}

type L2IngressSgRule struct {
	_             structs.HostLayout
	Proto         uint16
	PortLo        uint16
	PortHi        uint16
	Direction     uint8
	PeerKind      uint8
	PeerV4        uint32
	PeerPrefixlen uint8
	Verdict       uint8
	Pad           [2]uint8
}

type L2IngressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type L2IngressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	VpcId   uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
	AclId   uint32
}

type L2IngressTraceConfigVal struct {
	_            structs.HostLayout
	ExpiresNs    uint64
	CaptureFlags uint32
	Level        uint8
	Mode         uint8
	Pad          [2]uint8
}

type L2IngressTraceTupleKey struct {
	_     structs.HostLayout
	Scope uint8
	Proto uint8
	Pad   [2]uint8
	VpcId uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type L2IngressTraceTupleVal struct {
	_         structs.HostLayout
	TraceId   uint32
	Direction uint8
	Pad       [3]uint8
}

type L2IngressVirtualServiceFlowKey struct {
	_        structs.HostLayout
	SubnetId uint32
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Proto    uint8
	Pad      [3]uint8
}

type L2IngressVirtualServiceFlowVal struct {
	_          structs.HostLayout
	VpcId      uint32
	ServiceId  uint32
	PodIfindex uint32
	PodMac     [6]uint8
	ServiceMac [6]uint8
	Pad        [2]uint8
	_          [6]byte
	LastSeenNs uint64
}

type L2IngressVirtualServiceKey struct {
	_        structs.HostLayout
	SubnetId uint32
	DstIp    uint32
	DstPort  uint16
	Proto    uint8
	Pad      uint8
}

type L2IngressVirtualServiceVal struct {
	_          structs.HostLayout
	ServiceId  uint32
	TapIfindex uint32
	ServiceMac [6]uint8
	Pad        [2]uint8
	Flags      uint32
}

type L2IngressVpcEndpointKey struct {
	_       structs.HostLayout
	VpcId   uint32
	Address uint32
	Port    uint16
	Proto   uint8
	Pad     uint8
}

type L2IngressVpcEndpointVal struct {
	_         structs.HostLayout
	ClusterIp uint32
}

// LoadL2Ingress returns the embedded CollectionSpec for L2Ingress.
func LoadL2Ingress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_L2IngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load L2Ingress: %w", err)
	}

	return spec, err
}

// LoadL2IngressObjects loads L2Ingress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*L2IngressObjects
//	*L2IngressPrograms
//	*L2IngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadL2IngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadL2Ingress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// L2IngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L2IngressSpecs struct {
	L2IngressProgramSpecs
	L2IngressMapSpecs
	L2IngressVariableSpecs
}

// L2IngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L2IngressProgramSpecs struct {
	TcL2Ingress *ebpf.ProgramSpec `ebpf:"tc_l2_ingress"`
}

// L2IngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L2IngressMapSpecs struct {
	AclMetaMap            *ebpf.MapSpec `ebpf:"acl_meta_map"`
	AclRuleTable          *ebpf.MapSpec `ebpf:"acl_rule_table"`
	AclRulesInnerProto    *ebpf.MapSpec `ebpf:"acl_rules_inner_proto"`
	ArpTable              *ebpf.MapSpec `ebpf:"arp_table"`
	BackendMap            *ebpf.MapSpec `ebpf:"backend_map"`
	CtMap                 *ebpf.MapSpec `ebpf:"ct_map"`
	ExternalAddressPools  *ebpf.MapSpec `ebpf:"external_address_pools"`
	ExternalArpTable      *ebpf.MapSpec `ebpf:"external_arp_table"`
	Fdb                   *ebpf.MapSpec `ebpf:"fdb"`
	FibInner              *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap                *ebpf.MapSpec `ebpf:"fib_map"`
	HostUnderlay          *ebpf.MapSpec `ebpf:"host_underlay"`
	IfindexHostMac        *ebpf.MapSpec `ebpf:"ifindex_host_mac"`
	IfindexSubnet         *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	Ipv4FragMap           *ebpf.MapSpec `ebpf:"ipv4_frag_map"`
	L2Arp                 *ebpf.MapSpec `ebpf:"l2_arp"`
	L2ArpInner            *ebpf.MapSpec `ebpf:"l2_arp_inner"`
	L2BumLocal            *ebpf.MapSpec `ebpf:"l2_bum_local"`
	L2BumLocalInner       *ebpf.MapSpec `ebpf:"l2_bum_local_inner"`
	L2BumRemote           *ebpf.MapSpec `ebpf:"l2_bum_remote"`
	L2BumRemoteInner      *ebpf.MapSpec `ebpf:"l2_bum_remote_inner"`
	L2Fdb                 *ebpf.MapSpec `ebpf:"l2_fdb"`
	L2FdbInner            *ebpf.MapSpec `ebpf:"l2_fdb_inner"`
	L2Gateway             *ebpf.MapSpec `ebpf:"l2_gateway"`
	L2Ifindex             *ebpf.MapSpec `ebpf:"l2_ifindex"`
	L2NetworkMap          *ebpf.MapSpec `ebpf:"l2_network_map"`
	LbBackendMap          *ebpf.MapSpec `ebpf:"lb_backend_map"`
	LbServiceMap          *ebpf.MapSpec `ebpf:"lb_service_map"`
	NaptSrc               *ebpf.MapSpec `ebpf:"napt_src"`
	NatDnatMap            *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap            *ebpf.MapSpec `ebpf:"nat_snat_map"`
	NodeUnderlays         *ebpf.MapSpec `ebpf:"node_underlays"`
	PolicyCtMap           *ebpf.MapSpec `ebpf:"policy_ct_map"`
	PolicyEpochMap        *ebpf.MapSpec `ebpf:"policy_epoch_map"`
	ServiceAclMap         *ebpf.MapSpec `ebpf:"service_acl_map"`
	ServiceAffinityMap    *ebpf.MapSpec `ebpf:"service_affinity_map"`
	ServiceMap            *ebpf.MapSpec `ebpf:"service_map"`
	ServiceNatIp          *ebpf.MapSpec `ebpf:"service_nat_ip"`
	SgMembershipMap       *ebpf.MapSpec `ebpf:"sg_membership_map"`
	SgMetaMap             *ebpf.MapSpec `ebpf:"sg_meta_map"`
	SgRuleTable           *ebpf.MapSpec `ebpf:"sg_rule_table"`
	SgRulesInnerProto     *ebpf.MapSpec `ebpf:"sg_rules_inner_proto"`
	SubnetMap             *ebpf.MapSpec `ebpf:"subnet_map"`
	TgwFibInner           *ebpf.MapSpec `ebpf:"tgw_fib_inner"`
	TgwFibMap             *ebpf.MapSpec `ebpf:"tgw_fib_map"`
	TraceActive           *ebpf.MapSpec `ebpf:"trace_active"`
	TraceConfigMap        *ebpf.MapSpec `ebpf:"trace_config_map"`
	TraceEvents           *ebpf.MapSpec `ebpf:"trace_events"`
	TraceTupleMap         *ebpf.MapSpec `ebpf:"trace_tuple_map"`
	VirtualServiceFlowMap *ebpf.MapSpec `ebpf:"virtual_service_flow_map"`
	VirtualServiceMap     *ebpf.MapSpec `ebpf:"virtual_service_map"`
	VpcEndpointMap        *ebpf.MapSpec `ebpf:"vpc_endpoint_map"`
	VxlanIfindex          *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// L2IngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L2IngressVariableSpecs struct {
	AclRuleBtfAnchor *ebpf.VariableSpec `ebpf:"_acl_rule_btf_anchor"`
	SgRuleBtfAnchor  *ebpf.VariableSpec `ebpf:"_sg_rule_btf_anchor"`
}

// L2IngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadL2IngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type L2IngressObjects struct {
	L2IngressPrograms
	L2IngressMaps
	L2IngressVariables
}

func (o *L2IngressObjects) Close() error {
	return _L2IngressClose(
		&o.L2IngressPrograms,
		&o.L2IngressMaps,
	)
}

// L2IngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadL2IngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type L2IngressMaps struct {
	AclMetaMap            *ebpf.Map `ebpf:"acl_meta_map"`
	AclRuleTable          *ebpf.Map `ebpf:"acl_rule_table"`
	AclRulesInnerProto    *ebpf.Map `ebpf:"acl_rules_inner_proto"`
	ArpTable              *ebpf.Map `ebpf:"arp_table"`
	BackendMap            *ebpf.Map `ebpf:"backend_map"`
	CtMap                 *ebpf.Map `ebpf:"ct_map"`
	ExternalAddressPools  *ebpf.Map `ebpf:"external_address_pools"`
	ExternalArpTable      *ebpf.Map `ebpf:"external_arp_table"`
	Fdb                   *ebpf.Map `ebpf:"fdb"`
	FibInner              *ebpf.Map `ebpf:"fib_inner"`
	FibMap                *ebpf.Map `ebpf:"fib_map"`
	HostUnderlay          *ebpf.Map `ebpf:"host_underlay"`
	IfindexHostMac        *ebpf.Map `ebpf:"ifindex_host_mac"`
	IfindexSubnet         *ebpf.Map `ebpf:"ifindex_subnet"`
	Ipv4FragMap           *ebpf.Map `ebpf:"ipv4_frag_map"`
	L2Arp                 *ebpf.Map `ebpf:"l2_arp"`
	L2ArpInner            *ebpf.Map `ebpf:"l2_arp_inner"`
	L2BumLocal            *ebpf.Map `ebpf:"l2_bum_local"`
	L2BumLocalInner       *ebpf.Map `ebpf:"l2_bum_local_inner"`
	L2BumRemote           *ebpf.Map `ebpf:"l2_bum_remote"`
	L2BumRemoteInner      *ebpf.Map `ebpf:"l2_bum_remote_inner"`
	L2Fdb                 *ebpf.Map `ebpf:"l2_fdb"`
	L2FdbInner            *ebpf.Map `ebpf:"l2_fdb_inner"`
	L2Gateway             *ebpf.Map `ebpf:"l2_gateway"`
	L2Ifindex             *ebpf.Map `ebpf:"l2_ifindex"`
	L2NetworkMap          *ebpf.Map `ebpf:"l2_network_map"`
	LbBackendMap          *ebpf.Map `ebpf:"lb_backend_map"`
	LbServiceMap          *ebpf.Map `ebpf:"lb_service_map"`
	NaptSrc               *ebpf.Map `ebpf:"napt_src"`
	NatDnatMap            *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap            *ebpf.Map `ebpf:"nat_snat_map"`
	NodeUnderlays         *ebpf.Map `ebpf:"node_underlays"`
	PolicyCtMap           *ebpf.Map `ebpf:"policy_ct_map"`
	PolicyEpochMap        *ebpf.Map `ebpf:"policy_epoch_map"`
	ServiceAclMap         *ebpf.Map `ebpf:"service_acl_map"`
	ServiceAffinityMap    *ebpf.Map `ebpf:"service_affinity_map"`
	ServiceMap            *ebpf.Map `ebpf:"service_map"`
	ServiceNatIp          *ebpf.Map `ebpf:"service_nat_ip"`
	SgMembershipMap       *ebpf.Map `ebpf:"sg_membership_map"`
	SgMetaMap             *ebpf.Map `ebpf:"sg_meta_map"`
	SgRuleTable           *ebpf.Map `ebpf:"sg_rule_table"`
	SgRulesInnerProto     *ebpf.Map `ebpf:"sg_rules_inner_proto"`
	SubnetMap             *ebpf.Map `ebpf:"subnet_map"`
	TgwFibInner           *ebpf.Map `ebpf:"tgw_fib_inner"`
	TgwFibMap             *ebpf.Map `ebpf:"tgw_fib_map"`
	TraceActive           *ebpf.Map `ebpf:"trace_active"`
	TraceConfigMap        *ebpf.Map `ebpf:"trace_config_map"`
	TraceEvents           *ebpf.Map `ebpf:"trace_events"`
	TraceTupleMap         *ebpf.Map `ebpf:"trace_tuple_map"`
	VirtualServiceFlowMap *ebpf.Map `ebpf:"virtual_service_flow_map"`
	VirtualServiceMap     *ebpf.Map `ebpf:"virtual_service_map"`
	VpcEndpointMap        *ebpf.Map `ebpf:"vpc_endpoint_map"`
	VxlanIfindex          *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *L2IngressMaps) Close() error {
	return _L2IngressClose(
		m.AclMetaMap,
		m.AclRuleTable,
		m.AclRulesInnerProto,
		m.ArpTable,
		m.BackendMap,
		m.CtMap,
		m.ExternalAddressPools,
		m.ExternalArpTable,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostUnderlay,
		m.IfindexHostMac,
		m.IfindexSubnet,
		m.Ipv4FragMap,
		m.L2Arp,
		m.L2ArpInner,
		m.L2BumLocal,
		m.L2BumLocalInner,
		m.L2BumRemote,
		m.L2BumRemoteInner,
		m.L2Fdb,
		m.L2FdbInner,
		m.L2Gateway,
		m.L2Ifindex,
		m.L2NetworkMap,
		m.LbBackendMap,
		m.LbServiceMap,
		m.NaptSrc,
		m.NatDnatMap,
		m.NatSnatMap,
		m.NodeUnderlays,
		m.PolicyCtMap,
		m.PolicyEpochMap,
		m.ServiceAclMap,
		m.ServiceAffinityMap,
		m.ServiceMap,
		m.ServiceNatIp,
		m.SgMembershipMap,
		m.SgMetaMap,
		m.SgRuleTable,
		m.SgRulesInnerProto,
		m.SubnetMap,
		m.TgwFibInner,
		m.TgwFibMap,
		m.TraceActive,
		m.TraceConfigMap,
		m.TraceEvents,
		m.TraceTupleMap,
		m.VirtualServiceFlowMap,
		m.VirtualServiceMap,
		m.VpcEndpointMap,
		m.VxlanIfindex,
	)
}

// L2IngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadL2IngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type L2IngressVariables struct {
	AclRuleBtfAnchor *ebpf.Variable `ebpf:"_acl_rule_btf_anchor"`
	SgRuleBtfAnchor  *ebpf.Variable `ebpf:"_sg_rule_btf_anchor"`
}

// L2IngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadL2IngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type L2IngressPrograms struct {
	TcL2Ingress *ebpf.Program `ebpf:"tc_l2_ingress"`
}

func (p *L2IngressPrograms) Close() error {
	return _L2IngressClose(
		p.TcL2Ingress,
	)
}

func _L2IngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed l2ingress_bpfel.o
var _L2IngressBytes []byte
