// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NodeIngressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type NodeIngressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type NodeIngressBgpAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type NodeIngressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type NodeIngressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type NodeIngressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type NodeIngressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type NodeIngressHostIfaceVal struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	_       [2]byte
}

type NodeIngressIfindexHostMacKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type NodeIngressIfindexHostMacVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type NodeIngressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type NodeIngressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
}

type NodeIngressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type NodeIngressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type NodeIngressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type NodeIngressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
}

// LoadNodeIngress returns the embedded CollectionSpec for NodeIngress.
func LoadNodeIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NodeIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NodeIngress: %w", err)
	}

	return spec, err
}

// LoadNodeIngressObjects loads NodeIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NodeIngressObjects
//	*NodeIngressPrograms
//	*NodeIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNodeIngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNodeIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NodeIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodeIngressSpecs struct {
	NodeIngressProgramSpecs
	NodeIngressMapSpecs
	NodeIngressVariableSpecs
}

// NodeIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodeIngressProgramSpecs struct {
	TcNodeIngress *ebpf.ProgramSpec `ebpf:"tc_node_ingress"`
}

// NodeIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodeIngressMapSpecs struct {
	ArpTable        *ebpf.MapSpec `ebpf:"arp_table"`
	BgpAddressPools *ebpf.MapSpec `ebpf:"bgp_address_pools"`
	Fdb             *ebpf.MapSpec `ebpf:"fdb"`
	FibInner        *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap          *ebpf.MapSpec `ebpf:"fib_map"`
	HostIface       *ebpf.MapSpec `ebpf:"host_iface"`
	IfindexHostMac  *ebpf.MapSpec `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	NatDnatMap      *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.MapSpec `ebpf:"nat_snat_map"`
	SubnetMap       *ebpf.MapSpec `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// NodeIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodeIngressVariableSpecs struct {
}

// NodeIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNodeIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodeIngressObjects struct {
	NodeIngressPrograms
	NodeIngressMaps
	NodeIngressVariables
}

func (o *NodeIngressObjects) Close() error {
	return _NodeIngressClose(
		&o.NodeIngressPrograms,
		&o.NodeIngressMaps,
	)
}

// NodeIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNodeIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodeIngressMaps struct {
	ArpTable        *ebpf.Map `ebpf:"arp_table"`
	BgpAddressPools *ebpf.Map `ebpf:"bgp_address_pools"`
	Fdb             *ebpf.Map `ebpf:"fdb"`
	FibInner        *ebpf.Map `ebpf:"fib_inner"`
	FibMap          *ebpf.Map `ebpf:"fib_map"`
	HostIface       *ebpf.Map `ebpf:"host_iface"`
	IfindexHostMac  *ebpf.Map `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.Map `ebpf:"ifindex_subnet"`
	NatDnatMap      *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.Map `ebpf:"nat_snat_map"`
	SubnetMap       *ebpf.Map `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *NodeIngressMaps) Close() error {
	return _NodeIngressClose(
		m.ArpTable,
		m.BgpAddressPools,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostIface,
		m.IfindexHostMac,
		m.IfindexSubnet,
		m.NatDnatMap,
		m.NatSnatMap,
		m.SubnetMap,
		m.VxlanIfindex,
	)
}

// NodeIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNodeIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodeIngressVariables struct {
}

// NodeIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNodeIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodeIngressPrograms struct {
	TcNodeIngress *ebpf.Program `ebpf:"tc_node_ingress"`
}

func (p *NodeIngressPrograms) Close() error {
	return _NodeIngressClose(
		p.TcNodeIngress,
	)
}

func _NodeIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nodeingress_bpfeb.o
var _NodeIngressBytes []byte
