// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PodEgressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type PodEgressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodEgressBackendKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
	Index     uint32
}

type PodEgressBackendVal struct {
	_               structs.HostLayout
	BackendIp       uint32
	BackendPort     uint16
	Pad             [2]uint8
	BackendSubnetId uint32
}

type PodEgressBgpAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type PodEgressCtKey struct {
	_     structs.HostLayout
	Scope uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type PodEgressCtVal struct {
	_            structs.HostLayout
	NewSaddr     uint32
	NewDaddr     uint32
	NewSport     uint16
	NewDport     uint16
	NextSubnetId uint32
	Action       uint8
	State        uint8
	FlagsSeen    uint8
	Pad          uint8
	_            [4]byte
	LastSeenNs   uint64
}

type PodEgressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type PodEgressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type PodEgressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type PodEgressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type PodEgressIfindexHostMacKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodEgressIfindexHostMacVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodEgressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodEgressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodEgressNaptSrcKey struct {
	_            structs.HostLayout
	NatGatewayId uint32
}

type PodEgressNaptSrcVal struct {
	_      structs.HostLayout
	HostIp uint32
}

type PodEgressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type PodEgressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type PodEgressServiceKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
}

type PodEgressServiceVal struct {
	_            structs.HostLayout
	OwnerVpcId   uint32
	BackendCount uint32
	AffinitySec  uint32
	Pad          uint32
}

type PodEgressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodEgressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	VpcId   uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
}

// LoadPodEgress returns the embedded CollectionSpec for PodEgress.
func LoadPodEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PodEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PodEgress: %w", err)
	}

	return spec, err
}

// LoadPodEgressObjects loads PodEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PodEgressObjects
//	*PodEgressPrograms
//	*PodEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPodEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPodEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PodEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressSpecs struct {
	PodEgressProgramSpecs
	PodEgressMapSpecs
	PodEgressVariableSpecs
}

// PodEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressProgramSpecs struct {
	TcPodEgress *ebpf.ProgramSpec `ebpf:"tc_pod_egress"`
}

// PodEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressMapSpecs struct {
	ArpTable        *ebpf.MapSpec `ebpf:"arp_table"`
	BackendMap      *ebpf.MapSpec `ebpf:"backend_map"`
	BgpAddressPools *ebpf.MapSpec `ebpf:"bgp_address_pools"`
	CtMap           *ebpf.MapSpec `ebpf:"ct_map"`
	Fdb             *ebpf.MapSpec `ebpf:"fdb"`
	FibInner        *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap          *ebpf.MapSpec `ebpf:"fib_map"`
	HostUnderlay    *ebpf.MapSpec `ebpf:"host_underlay"`
	IfindexHostMac  *ebpf.MapSpec `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	NaptSrc         *ebpf.MapSpec `ebpf:"napt_src"`
	NatDnatMap      *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.MapSpec `ebpf:"nat_snat_map"`
	ServiceMap      *ebpf.MapSpec `ebpf:"service_map"`
	SubnetMap       *ebpf.MapSpec `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// PodEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressVariableSpecs struct {
}

// PodEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressObjects struct {
	PodEgressPrograms
	PodEgressMaps
	PodEgressVariables
}

func (o *PodEgressObjects) Close() error {
	return _PodEgressClose(
		&o.PodEgressPrograms,
		&o.PodEgressMaps,
	)
}

// PodEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressMaps struct {
	ArpTable        *ebpf.Map `ebpf:"arp_table"`
	BackendMap      *ebpf.Map `ebpf:"backend_map"`
	BgpAddressPools *ebpf.Map `ebpf:"bgp_address_pools"`
	CtMap           *ebpf.Map `ebpf:"ct_map"`
	Fdb             *ebpf.Map `ebpf:"fdb"`
	FibInner        *ebpf.Map `ebpf:"fib_inner"`
	FibMap          *ebpf.Map `ebpf:"fib_map"`
	HostUnderlay    *ebpf.Map `ebpf:"host_underlay"`
	IfindexHostMac  *ebpf.Map `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.Map `ebpf:"ifindex_subnet"`
	NaptSrc         *ebpf.Map `ebpf:"napt_src"`
	NatDnatMap      *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.Map `ebpf:"nat_snat_map"`
	ServiceMap      *ebpf.Map `ebpf:"service_map"`
	SubnetMap       *ebpf.Map `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *PodEgressMaps) Close() error {
	return _PodEgressClose(
		m.ArpTable,
		m.BackendMap,
		m.BgpAddressPools,
		m.CtMap,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostUnderlay,
		m.IfindexHostMac,
		m.IfindexSubnet,
		m.NaptSrc,
		m.NatDnatMap,
		m.NatSnatMap,
		m.ServiceMap,
		m.SubnetMap,
		m.VxlanIfindex,
	)
}

// PodEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressVariables struct {
}

// PodEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressPrograms struct {
	TcPodEgress *ebpf.Program `ebpf:"tc_pod_egress"`
}

func (p *PodEgressPrograms) Close() error {
	return _PodEgressClose(
		p.TcPodEgress,
	)
}

func _PodEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed podegress_bpfel.o
var _PodEgressBytes []byte
