// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PodEgressAclMetaVal struct {
	_               structs.HostLayout
	IngressCount    uint32
	EgressCount     uint32
	RulesetVersion  uint64
	HasIngressRules uint8
	HasEgressRules  uint8
	Pad             [6]uint8
}

type PodEgressAclRule struct {
	_         structs.HostLayout
	Proto     uint16
	PortLo    uint16
	PortHi    uint16
	Priority  uint16
	PeerV4    uint32
	Direction uint8
	Prefixlen uint8
	Verdict   uint8
	Pad       uint8
}

type PodEgressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type PodEgressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodEgressBackendKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
	Index     uint32
}

type PodEgressBackendVal struct {
	_               structs.HostLayout
	BackendIp       uint32
	BackendPort     uint16
	Kind            uint8
	Pad             uint8
	BackendSubnetId uint32
}

type PodEgressCtKey struct {
	_     structs.HostLayout
	Scope uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type PodEgressCtVal struct {
	_            structs.HostLayout
	NewSaddr     uint32
	NewDaddr     uint32
	NewSport     uint16
	NewDport     uint16
	NextSubnetId uint32
	Action       uint8
	State        uint8
	FlagsSeen    uint8
	Pad          uint8
	_            [4]byte
	LastSeenNs   uint64
}

type PodEgressExternalAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type PodEgressExternalArpKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Ipaddr  uint32
}

type PodEgressExternalArpVal struct {
	_   structs.HostLayout
	Mac [6]uint8
	Pad [2]uint8
}

type PodEgressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type PodEgressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type PodEgressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type PodEgressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type PodEgressIfindexHostMacKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodEgressIfindexHostMacVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodEgressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodEgressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipv4     uint32
}

type PodEgressIpv4FragKey struct {
	_     structs.HostLayout
	VpcId uint32
	Saddr uint32
	Daddr uint32
	Id    uint16
	Proto uint8
	Pad   uint8
}

type PodEgressIpv4FragVal struct {
	_          structs.HostLayout
	Sport      uint16
	Dport      uint16
	_          [4]byte
	LastSeenNs uint64
}

type PodEgressLbBackendKey struct {
	_     structs.HostLayout
	Vip   uint32
	Port  uint16
	Proto uint8
	Pad   uint8
	Index uint32
}

type PodEgressLbBackendVal struct {
	_               structs.HostLayout
	BackendIp       uint32
	BackendPort     uint16
	Pad             [2]uint8
	BackendSubnetId uint32
}

type PodEgressLbServiceKey struct {
	_     structs.HostLayout
	Vip   uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type PodEgressLbServiceVal struct {
	_            structs.HostLayout
	BackendCount uint32
	Gen          uint32
	Flags        uint32
	Pad          uint32
}

type PodEgressNaptSrcKey struct {
	_            structs.HostLayout
	NatGatewayId uint32
}

type PodEgressNaptSrcVal struct {
	_      structs.HostLayout
	HostIp uint32
}

type PodEgressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type PodEgressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type PodEgressPolicyCtKey struct {
	_     structs.HostLayout
	Epoch uint32
	Scope uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Hook  uint8
	Pad   [2]uint8
}

type PodEgressPolicyCtVal struct {
	_          structs.HostLayout
	State      uint8
	FlagsSeen  uint8
	Pad        [2]uint8
	_          [4]byte
	LastSeenNs uint64
}

type PodEgressServiceAclKey struct {
	_           structs.HostLayout
	ClusterIp   uint32
	Port        uint16
	Proto       uint8
	Pad         uint8
	CallerVpcId uint32
}

type PodEgressServiceAffinityKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
	ClientIp  uint32
}

type PodEgressServiceAffinityVal struct {
	_            structs.HostLayout
	BackendIndex uint32
	BackendGen   uint32
	ExpiresAtNs  uint64
}

type PodEgressServiceKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
}

type PodEgressServiceVal struct {
	_            structs.HostLayout
	OwnerVpcId   uint32
	BackendCount uint32
	AffinitySec  uint32
	Flags        uint32
	Gen          uint32
}

type PodEgressSgMembershipKey struct {
	_     structs.HostLayout
	VpcId uint32
	Ipv4  uint32
}

type PodEgressSgMembershipVal struct {
	_     structs.HostLayout
	Count uint8
	Pad   [3]uint8
	Sgs   [2]uint32
}

type PodEgressSgMetaVal struct {
	_              structs.HostLayout
	IngressCount   uint32
	EgressCount    uint32
	RulesetVersion uint32
	HasEgressRules uint8
	Pad            [3]uint8
}

type PodEgressSgRule struct {
	_             structs.HostLayout
	Proto         uint16
	PortLo        uint16
	PortHi        uint16
	Direction     uint8
	PeerKind      uint8
	PeerV4        uint32
	PeerPrefixlen uint8
	Verdict       uint8
	Pad           [2]uint8
}

type PodEgressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodEgressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	VpcId   uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
	AclId   uint32
}

type PodEgressTraceConfigVal struct {
	_            structs.HostLayout
	ExpiresNs    uint64
	CaptureFlags uint32
	Level        uint8
	Mode         uint8
	Pad          [2]uint8
}

type PodEgressTraceEmitArgs struct {
	_         structs.HostLayout
	TraceId   uint32
	Reason    uint16
	Hook      uint8
	Scope     uint8
	Proto     uint8
	Verdict   uint8
	Direction uint8
	Pad0      uint8
	Ifindex   uint32
	VpcId     uint32
	SubnetId  uint32
	Saddr     uint32
	Daddr     uint32
	Sport     uint16
	Dport     uint16
	Saddr2    uint32
	Daddr2    uint32
	Sport2    uint16
	Dport2    uint16
	Aux1      uint32
	Aux2      uint32
}

type PodEgressTraceNatEvent struct {
	_           structs.HostLayout
	VpcId       uint32
	SubnetId    uint32
	Reason      uint16
	Hook        uint8
	Scope       uint8
	Proto       uint8
	Pad         [3]uint8
	BeforeSaddr uint32
	BeforeDaddr uint32
	BeforeSport uint16
	BeforeDport uint16
	AfterSaddr  uint32
	AfterDaddr  uint32
	AfterSport  uint16
	AfterDport  uint16
}

type PodEgressTraceTupleKey struct {
	_     structs.HostLayout
	Scope uint8
	Proto uint8
	Pad   [2]uint8
	VpcId uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type PodEgressTraceTupleVal struct {
	_         structs.HostLayout
	TraceId   uint32
	Direction uint8
	Pad       [3]uint8
}

type PodEgressVirtualServiceFlowKey struct {
	_        structs.HostLayout
	SubnetId uint32
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Proto    uint8
	Pad      [3]uint8
}

type PodEgressVirtualServiceFlowVal struct {
	_          structs.HostLayout
	VpcId      uint32
	ServiceId  uint32
	PodIfindex uint32
	PodMac     [6]uint8
	ServiceMac [6]uint8
	Pad        [2]uint8
	_          [6]byte
	LastSeenNs uint64
}

type PodEgressVirtualServiceKey struct {
	_        structs.HostLayout
	SubnetId uint32
	DstIp    uint32
	DstPort  uint16
	Proto    uint8
	Pad      uint8
}

type PodEgressVirtualServiceVal struct {
	_          structs.HostLayout
	ServiceId  uint32
	TapIfindex uint32
	ServiceMac [6]uint8
	Pad        [2]uint8
	Flags      uint32
}

type PodEgressVpcEndpointKey struct {
	_       structs.HostLayout
	VpcId   uint32
	Address uint32
	Port    uint16
	Proto   uint8
	Pad     uint8
}

type PodEgressVpcEndpointVal struct {
	_         structs.HostLayout
	ClusterIp uint32
}

// LoadPodEgress returns the embedded CollectionSpec for PodEgress.
func LoadPodEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PodEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PodEgress: %w", err)
	}

	return spec, err
}

// LoadPodEgressObjects loads PodEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PodEgressObjects
//	*PodEgressPrograms
//	*PodEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPodEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPodEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PodEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressSpecs struct {
	PodEgressProgramSpecs
	PodEgressMapSpecs
	PodEgressVariableSpecs
}

// PodEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressProgramSpecs struct {
	TcPodEgress *ebpf.ProgramSpec `ebpf:"tc_pod_egress"`
}

// PodEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressMapSpecs struct {
	AclMetaMap            *ebpf.MapSpec `ebpf:"acl_meta_map"`
	AclRuleTable          *ebpf.MapSpec `ebpf:"acl_rule_table"`
	AclRulesInnerProto    *ebpf.MapSpec `ebpf:"acl_rules_inner_proto"`
	ArpTable              *ebpf.MapSpec `ebpf:"arp_table"`
	BackendMap            *ebpf.MapSpec `ebpf:"backend_map"`
	CtMap                 *ebpf.MapSpec `ebpf:"ct_map"`
	ExternalAddressPools  *ebpf.MapSpec `ebpf:"external_address_pools"`
	ExternalArpTable      *ebpf.MapSpec `ebpf:"external_arp_table"`
	Fdb                   *ebpf.MapSpec `ebpf:"fdb"`
	FibInner              *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap                *ebpf.MapSpec `ebpf:"fib_map"`
	HostUnderlay          *ebpf.MapSpec `ebpf:"host_underlay"`
	IfindexHostMac        *ebpf.MapSpec `ebpf:"ifindex_host_mac"`
	IfindexSubnet         *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	Ipv4FragMap           *ebpf.MapSpec `ebpf:"ipv4_frag_map"`
	LbBackendMap          *ebpf.MapSpec `ebpf:"lb_backend_map"`
	LbServiceMap          *ebpf.MapSpec `ebpf:"lb_service_map"`
	NaptSrc               *ebpf.MapSpec `ebpf:"napt_src"`
	NatDnatMap            *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap            *ebpf.MapSpec `ebpf:"nat_snat_map"`
	NodeUnderlays         *ebpf.MapSpec `ebpf:"node_underlays"`
	PodEgressEmitScratch  *ebpf.MapSpec `ebpf:"pod_egress_emit_scratch"`
	PodEgressNatScratch   *ebpf.MapSpec `ebpf:"pod_egress_nat_scratch"`
	PolicyCtMap           *ebpf.MapSpec `ebpf:"policy_ct_map"`
	PolicyEpochMap        *ebpf.MapSpec `ebpf:"policy_epoch_map"`
	ServiceAclMap         *ebpf.MapSpec `ebpf:"service_acl_map"`
	ServiceAffinityMap    *ebpf.MapSpec `ebpf:"service_affinity_map"`
	ServiceMap            *ebpf.MapSpec `ebpf:"service_map"`
	ServiceNatIp          *ebpf.MapSpec `ebpf:"service_nat_ip"`
	SgMembershipMap       *ebpf.MapSpec `ebpf:"sg_membership_map"`
	SgMetaMap             *ebpf.MapSpec `ebpf:"sg_meta_map"`
	SgRuleTable           *ebpf.MapSpec `ebpf:"sg_rule_table"`
	SgRulesInnerProto     *ebpf.MapSpec `ebpf:"sg_rules_inner_proto"`
	SubnetMap             *ebpf.MapSpec `ebpf:"subnet_map"`
	TgwFibInner           *ebpf.MapSpec `ebpf:"tgw_fib_inner"`
	TgwFibMap             *ebpf.MapSpec `ebpf:"tgw_fib_map"`
	TraceActive           *ebpf.MapSpec `ebpf:"trace_active"`
	TraceConfigMap        *ebpf.MapSpec `ebpf:"trace_config_map"`
	TraceEvents           *ebpf.MapSpec `ebpf:"trace_events"`
	TraceTupleMap         *ebpf.MapSpec `ebpf:"trace_tuple_map"`
	VirtualServiceFlowMap *ebpf.MapSpec `ebpf:"virtual_service_flow_map"`
	VirtualServiceMap     *ebpf.MapSpec `ebpf:"virtual_service_map"`
	VpcEndpointMap        *ebpf.MapSpec `ebpf:"vpc_endpoint_map"`
	VxlanIfindex          *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// PodEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressVariableSpecs struct {
	AclRuleBtfAnchor *ebpf.VariableSpec `ebpf:"_acl_rule_btf_anchor"`
	SgRuleBtfAnchor  *ebpf.VariableSpec `ebpf:"_sg_rule_btf_anchor"`
}

// PodEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressObjects struct {
	PodEgressPrograms
	PodEgressMaps
	PodEgressVariables
}

func (o *PodEgressObjects) Close() error {
	return _PodEgressClose(
		&o.PodEgressPrograms,
		&o.PodEgressMaps,
	)
}

// PodEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressMaps struct {
	AclMetaMap            *ebpf.Map `ebpf:"acl_meta_map"`
	AclRuleTable          *ebpf.Map `ebpf:"acl_rule_table"`
	AclRulesInnerProto    *ebpf.Map `ebpf:"acl_rules_inner_proto"`
	ArpTable              *ebpf.Map `ebpf:"arp_table"`
	BackendMap            *ebpf.Map `ebpf:"backend_map"`
	CtMap                 *ebpf.Map `ebpf:"ct_map"`
	ExternalAddressPools  *ebpf.Map `ebpf:"external_address_pools"`
	ExternalArpTable      *ebpf.Map `ebpf:"external_arp_table"`
	Fdb                   *ebpf.Map `ebpf:"fdb"`
	FibInner              *ebpf.Map `ebpf:"fib_inner"`
	FibMap                *ebpf.Map `ebpf:"fib_map"`
	HostUnderlay          *ebpf.Map `ebpf:"host_underlay"`
	IfindexHostMac        *ebpf.Map `ebpf:"ifindex_host_mac"`
	IfindexSubnet         *ebpf.Map `ebpf:"ifindex_subnet"`
	Ipv4FragMap           *ebpf.Map `ebpf:"ipv4_frag_map"`
	LbBackendMap          *ebpf.Map `ebpf:"lb_backend_map"`
	LbServiceMap          *ebpf.Map `ebpf:"lb_service_map"`
	NaptSrc               *ebpf.Map `ebpf:"napt_src"`
	NatDnatMap            *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap            *ebpf.Map `ebpf:"nat_snat_map"`
	NodeUnderlays         *ebpf.Map `ebpf:"node_underlays"`
	PodEgressEmitScratch  *ebpf.Map `ebpf:"pod_egress_emit_scratch"`
	PodEgressNatScratch   *ebpf.Map `ebpf:"pod_egress_nat_scratch"`
	PolicyCtMap           *ebpf.Map `ebpf:"policy_ct_map"`
	PolicyEpochMap        *ebpf.Map `ebpf:"policy_epoch_map"`
	ServiceAclMap         *ebpf.Map `ebpf:"service_acl_map"`
	ServiceAffinityMap    *ebpf.Map `ebpf:"service_affinity_map"`
	ServiceMap            *ebpf.Map `ebpf:"service_map"`
	ServiceNatIp          *ebpf.Map `ebpf:"service_nat_ip"`
	SgMembershipMap       *ebpf.Map `ebpf:"sg_membership_map"`
	SgMetaMap             *ebpf.Map `ebpf:"sg_meta_map"`
	SgRuleTable           *ebpf.Map `ebpf:"sg_rule_table"`
	SgRulesInnerProto     *ebpf.Map `ebpf:"sg_rules_inner_proto"`
	SubnetMap             *ebpf.Map `ebpf:"subnet_map"`
	TgwFibInner           *ebpf.Map `ebpf:"tgw_fib_inner"`
	TgwFibMap             *ebpf.Map `ebpf:"tgw_fib_map"`
	TraceActive           *ebpf.Map `ebpf:"trace_active"`
	TraceConfigMap        *ebpf.Map `ebpf:"trace_config_map"`
	TraceEvents           *ebpf.Map `ebpf:"trace_events"`
	TraceTupleMap         *ebpf.Map `ebpf:"trace_tuple_map"`
	VirtualServiceFlowMap *ebpf.Map `ebpf:"virtual_service_flow_map"`
	VirtualServiceMap     *ebpf.Map `ebpf:"virtual_service_map"`
	VpcEndpointMap        *ebpf.Map `ebpf:"vpc_endpoint_map"`
	VxlanIfindex          *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *PodEgressMaps) Close() error {
	return _PodEgressClose(
		m.AclMetaMap,
		m.AclRuleTable,
		m.AclRulesInnerProto,
		m.ArpTable,
		m.BackendMap,
		m.CtMap,
		m.ExternalAddressPools,
		m.ExternalArpTable,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostUnderlay,
		m.IfindexHostMac,
		m.IfindexSubnet,
		m.Ipv4FragMap,
		m.LbBackendMap,
		m.LbServiceMap,
		m.NaptSrc,
		m.NatDnatMap,
		m.NatSnatMap,
		m.NodeUnderlays,
		m.PodEgressEmitScratch,
		m.PodEgressNatScratch,
		m.PolicyCtMap,
		m.PolicyEpochMap,
		m.ServiceAclMap,
		m.ServiceAffinityMap,
		m.ServiceMap,
		m.ServiceNatIp,
		m.SgMembershipMap,
		m.SgMetaMap,
		m.SgRuleTable,
		m.SgRulesInnerProto,
		m.SubnetMap,
		m.TgwFibInner,
		m.TgwFibMap,
		m.TraceActive,
		m.TraceConfigMap,
		m.TraceEvents,
		m.TraceTupleMap,
		m.VirtualServiceFlowMap,
		m.VirtualServiceMap,
		m.VpcEndpointMap,
		m.VxlanIfindex,
	)
}

// PodEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressVariables struct {
	AclRuleBtfAnchor *ebpf.Variable `ebpf:"_acl_rule_btf_anchor"`
	SgRuleBtfAnchor  *ebpf.Variable `ebpf:"_sg_rule_btf_anchor"`
}

// PodEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressPrograms struct {
	TcPodEgress *ebpf.Program `ebpf:"tc_pod_egress"`
}

func (p *PodEgressPrograms) Close() error {
	return _PodEgressClose(
		p.TcPodEgress,
	)
}

func _PodEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed podegress_bpfeb.o
var _PodEgressBytes []byte
