// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PodEgressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type PodEgressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodEgressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type PodEgressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type PodEgressHostIfaceVal struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	_       [2]byte
}

type PodEgressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodEgressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
	GwMac    [6]uint8
	_        [2]byte
	GwAddr   uint32
	Mask     uint32
}

// LoadPodEgress returns the embedded CollectionSpec for PodEgress.
func LoadPodEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PodEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PodEgress: %w", err)
	}

	return spec, err
}

// LoadPodEgressObjects loads PodEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PodEgressObjects
//	*PodEgressPrograms
//	*PodEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPodEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPodEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PodEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressSpecs struct {
	PodEgressProgramSpecs
	PodEgressMapSpecs
	PodEgressVariableSpecs
}

// PodEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressProgramSpecs struct {
	TcPodEgress *ebpf.ProgramSpec `ebpf:"tc_pod_egress"`
}

// PodEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressMapSpecs struct {
	ArpTable      *ebpf.MapSpec `ebpf:"arp_table"`
	Fdb           *ebpf.MapSpec `ebpf:"fdb"`
	HostIface     *ebpf.MapSpec `ebpf:"host_iface"`
	IfindexSubnet *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	VxlanIfindex  *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// PodEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressVariableSpecs struct {
}

// PodEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressObjects struct {
	PodEgressPrograms
	PodEgressMaps
	PodEgressVariables
}

func (o *PodEgressObjects) Close() error {
	return _PodEgressClose(
		&o.PodEgressPrograms,
		&o.PodEgressMaps,
	)
}

// PodEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressMaps struct {
	ArpTable      *ebpf.Map `ebpf:"arp_table"`
	Fdb           *ebpf.Map `ebpf:"fdb"`
	HostIface     *ebpf.Map `ebpf:"host_iface"`
	IfindexSubnet *ebpf.Map `ebpf:"ifindex_subnet"`
	VxlanIfindex  *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *PodEgressMaps) Close() error {
	return _PodEgressClose(
		m.ArpTable,
		m.Fdb,
		m.HostIface,
		m.IfindexSubnet,
		m.VxlanIfindex,
	)
}

// PodEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressVariables struct {
}

// PodEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressPrograms struct {
	TcPodEgress *ebpf.Program `ebpf:"tc_pod_egress"`
}

func (p *PodEgressPrograms) Close() error {
	return _PodEgressClose(
		p.TcPodEgress,
	)
}

func _PodEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed podegress_bpfel.o
var _PodEgressBytes []byte
