// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PodEgressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type PodEgressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodEgressBgpAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type PodEgressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type PodEgressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type PodEgressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type PodEgressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type PodEgressHostIfaceVal struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	_       [2]byte
}

type PodEgressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodEgressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodEgressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type PodEgressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type PodEgressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodEgressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
}

// LoadPodEgress returns the embedded CollectionSpec for PodEgress.
func LoadPodEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PodEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PodEgress: %w", err)
	}

	return spec, err
}

// LoadPodEgressObjects loads PodEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PodEgressObjects
//	*PodEgressPrograms
//	*PodEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPodEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPodEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PodEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressSpecs struct {
	PodEgressProgramSpecs
	PodEgressMapSpecs
	PodEgressVariableSpecs
}

// PodEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressProgramSpecs struct {
	TcPodEgress *ebpf.ProgramSpec `ebpf:"tc_pod_egress"`
}

// PodEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressMapSpecs struct {
	ArpTable        *ebpf.MapSpec `ebpf:"arp_table"`
	BgpAddressPools *ebpf.MapSpec `ebpf:"bgp_address_pools"`
	Fdb             *ebpf.MapSpec `ebpf:"fdb"`
	FibInner        *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap          *ebpf.MapSpec `ebpf:"fib_map"`
	HostIface       *ebpf.MapSpec `ebpf:"host_iface"`
	IfindexSubnet   *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	NatDnatMap      *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.MapSpec `ebpf:"nat_snat_map"`
	SubnetMap       *ebpf.MapSpec `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// PodEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodEgressVariableSpecs struct {
}

// PodEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressObjects struct {
	PodEgressPrograms
	PodEgressMaps
	PodEgressVariables
}

func (o *PodEgressObjects) Close() error {
	return _PodEgressClose(
		&o.PodEgressPrograms,
		&o.PodEgressMaps,
	)
}

// PodEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressMaps struct {
	ArpTable        *ebpf.Map `ebpf:"arp_table"`
	BgpAddressPools *ebpf.Map `ebpf:"bgp_address_pools"`
	Fdb             *ebpf.Map `ebpf:"fdb"`
	FibInner        *ebpf.Map `ebpf:"fib_inner"`
	FibMap          *ebpf.Map `ebpf:"fib_map"`
	HostIface       *ebpf.Map `ebpf:"host_iface"`
	IfindexSubnet   *ebpf.Map `ebpf:"ifindex_subnet"`
	NatDnatMap      *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.Map `ebpf:"nat_snat_map"`
	SubnetMap       *ebpf.Map `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *PodEgressMaps) Close() error {
	return _PodEgressClose(
		m.ArpTable,
		m.BgpAddressPools,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostIface,
		m.IfindexSubnet,
		m.NatDnatMap,
		m.NatSnatMap,
		m.SubnetMap,
		m.VxlanIfindex,
	)
}

// PodEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressVariables struct {
}

// PodEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPodEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodEgressPrograms struct {
	TcPodEgress *ebpf.Program `ebpf:"tc_pod_egress"`
}

func (p *PodEgressPrograms) Close() error {
	return _PodEgressClose(
		p.TcPodEgress,
	)
}

func _PodEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed podegress_bpfeb.o
var _PodEgressBytes []byte
