// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PodIngressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type PodIngressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodIngressBackendKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
	Index     uint32
}

type PodIngressBackendVal struct {
	_               structs.HostLayout
	BackendIp       uint32
	BackendPort     uint16
	Pad             [2]uint8
	BackendSubnetId uint32
}

type PodIngressBgpAddressPoolsKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type PodIngressCtKey struct {
	_     structs.HostLayout
	Scope uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type PodIngressCtVal struct {
	_            structs.HostLayout
	NewSaddr     uint32
	NewDaddr     uint32
	NewSport     uint16
	NewDport     uint16
	NextSubnetId uint32
	Action       uint8
	State        uint8
	FlagsSeen    uint8
	Pad          uint8
	_            [4]byte
	LastSeenNs   uint64
}

type PodIngressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type PodIngressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type PodIngressFibKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Dst       uint32
}

type PodIngressFibVal struct {
	_        structs.HostLayout
	Type     uint8
	Dmac     [6]uint8
	Smac     [6]uint8
	_        [3]byte
	SubnetId uint32
	Oif      uint32
}

type PodIngressIfindexHostMacKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodIngressIfindexHostMacVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type PodIngressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type PodIngressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodIngressNaptSrcKey struct {
	_            structs.HostLayout
	NatGatewayId uint32
}

type PodIngressNaptSrcVal struct {
	_      structs.HostLayout
	HostIp uint32
}

type PodIngressNatInside struct {
	_        structs.HostLayout
	SubnetId uint32
	Addr     uint32
}

type PodIngressNatOutside struct {
	_    structs.HostLayout
	Addr uint32
}

type PodIngressServiceKey struct {
	_         structs.HostLayout
	ClusterIp uint32
	Port      uint16
	Proto     uint8
	Pad       uint8
}

type PodIngressServiceVal struct {
	_            structs.HostLayout
	OwnerVpcId   uint32
	BackendCount uint32
	AffinitySec  uint32
	Pad          uint32
}

type PodIngressSubnetKey struct {
	_        structs.HostLayout
	SubnetId uint32
}

type PodIngressSubnetVal struct {
	_       structs.HostLayout
	TableId uint32
	VpcId   uint32
	GwMac   [6]uint8
	_       [2]byte
	GwAddr  uint32
	Mask    uint32
}

// LoadPodIngress returns the embedded CollectionSpec for PodIngress.
func LoadPodIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PodIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PodIngress: %w", err)
	}

	return spec, err
}

// LoadPodIngressObjects loads PodIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PodIngressObjects
//	*PodIngressPrograms
//	*PodIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPodIngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPodIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PodIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodIngressSpecs struct {
	PodIngressProgramSpecs
	PodIngressMapSpecs
	PodIngressVariableSpecs
}

// PodIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodIngressProgramSpecs struct {
	TcPodIngress *ebpf.ProgramSpec `ebpf:"tc_pod_ingress"`
}

// PodIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodIngressMapSpecs struct {
	ArpTable        *ebpf.MapSpec `ebpf:"arp_table"`
	BackendMap      *ebpf.MapSpec `ebpf:"backend_map"`
	BgpAddressPools *ebpf.MapSpec `ebpf:"bgp_address_pools"`
	CtMap           *ebpf.MapSpec `ebpf:"ct_map"`
	Fdb             *ebpf.MapSpec `ebpf:"fdb"`
	FibInner        *ebpf.MapSpec `ebpf:"fib_inner"`
	FibMap          *ebpf.MapSpec `ebpf:"fib_map"`
	HostUnderlay    *ebpf.MapSpec `ebpf:"host_underlay"`
	IfindexHostMac  *ebpf.MapSpec `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	NaptSrc         *ebpf.MapSpec `ebpf:"napt_src"`
	NatDnatMap      *ebpf.MapSpec `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.MapSpec `ebpf:"nat_snat_map"`
	ServiceMap      *ebpf.MapSpec `ebpf:"service_map"`
	SubnetMap       *ebpf.MapSpec `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// PodIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PodIngressVariableSpecs struct {
}

// PodIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPodIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodIngressObjects struct {
	PodIngressPrograms
	PodIngressMaps
	PodIngressVariables
}

func (o *PodIngressObjects) Close() error {
	return _PodIngressClose(
		&o.PodIngressPrograms,
		&o.PodIngressMaps,
	)
}

// PodIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPodIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodIngressMaps struct {
	ArpTable        *ebpf.Map `ebpf:"arp_table"`
	BackendMap      *ebpf.Map `ebpf:"backend_map"`
	BgpAddressPools *ebpf.Map `ebpf:"bgp_address_pools"`
	CtMap           *ebpf.Map `ebpf:"ct_map"`
	Fdb             *ebpf.Map `ebpf:"fdb"`
	FibInner        *ebpf.Map `ebpf:"fib_inner"`
	FibMap          *ebpf.Map `ebpf:"fib_map"`
	HostUnderlay    *ebpf.Map `ebpf:"host_underlay"`
	IfindexHostMac  *ebpf.Map `ebpf:"ifindex_host_mac"`
	IfindexSubnet   *ebpf.Map `ebpf:"ifindex_subnet"`
	NaptSrc         *ebpf.Map `ebpf:"napt_src"`
	NatDnatMap      *ebpf.Map `ebpf:"nat_dnat_map"`
	NatSnatMap      *ebpf.Map `ebpf:"nat_snat_map"`
	ServiceMap      *ebpf.Map `ebpf:"service_map"`
	SubnetMap       *ebpf.Map `ebpf:"subnet_map"`
	VxlanIfindex    *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *PodIngressMaps) Close() error {
	return _PodIngressClose(
		m.ArpTable,
		m.BackendMap,
		m.BgpAddressPools,
		m.CtMap,
		m.Fdb,
		m.FibInner,
		m.FibMap,
		m.HostUnderlay,
		m.IfindexHostMac,
		m.IfindexSubnet,
		m.NaptSrc,
		m.NatDnatMap,
		m.NatSnatMap,
		m.ServiceMap,
		m.SubnetMap,
		m.VxlanIfindex,
	)
}

// PodIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPodIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodIngressVariables struct {
}

// PodIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPodIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type PodIngressPrograms struct {
	TcPodIngress *ebpf.Program `ebpf:"tc_pod_ingress"`
}

func (p *PodIngressPrograms) Close() error {
	return _PodIngressClose(
		p.TcPodIngress,
	)
}

func _PodIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed podingress_bpfeb.o
var _PodIngressBytes []byte
