// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type VxlanIngressArpTableKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Ipaddr   uint32
}

type VxlanIngressArpTableVal struct {
	_   structs.HostLayout
	Mac [6]uint8
}

type VxlanIngressFdbKey struct {
	_        structs.HostLayout
	SubnetId uint32
	Mac      [6]uint8
	_        [2]byte
}

type VxlanIngressFdbVal struct {
	_       structs.HostLayout
	Ifindex uint32
	VtepIp  uint32
}

type VxlanIngressHostIfaceVal struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	_       [2]byte
}

type VxlanIngressIfindexSubnetKey struct {
	_       structs.HostLayout
	Ifindex uint32
}

type VxlanIngressIfindexSubnetVal struct {
	_        structs.HostLayout
	SubnetId uint32
	GwMac    [6]uint8
	_        [2]byte
	GwAddr   uint32
	Mask     uint32
}

// LoadVxlanIngress returns the embedded CollectionSpec for VxlanIngress.
func LoadVxlanIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VxlanIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load VxlanIngress: %w", err)
	}

	return spec, err
}

// LoadVxlanIngressObjects loads VxlanIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*VxlanIngressObjects
//	*VxlanIngressPrograms
//	*VxlanIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadVxlanIngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadVxlanIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// VxlanIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanIngressSpecs struct {
	VxlanIngressProgramSpecs
	VxlanIngressMapSpecs
	VxlanIngressVariableSpecs
}

// VxlanIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanIngressProgramSpecs struct {
	TcVxlanIngressEntry *ebpf.ProgramSpec `ebpf:"tc_vxlan_ingress_entry"`
}

// VxlanIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanIngressMapSpecs struct {
	ArpTable      *ebpf.MapSpec `ebpf:"arp_table"`
	Fdb           *ebpf.MapSpec `ebpf:"fdb"`
	HostIface     *ebpf.MapSpec `ebpf:"host_iface"`
	IfindexSubnet *ebpf.MapSpec `ebpf:"ifindex_subnet"`
	VxlanIfindex  *ebpf.MapSpec `ebpf:"vxlan_ifindex"`
}

// VxlanIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanIngressVariableSpecs struct {
}

// VxlanIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanIngressObjects struct {
	VxlanIngressPrograms
	VxlanIngressMaps
	VxlanIngressVariables
}

func (o *VxlanIngressObjects) Close() error {
	return _VxlanIngressClose(
		&o.VxlanIngressPrograms,
		&o.VxlanIngressMaps,
	)
}

// VxlanIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanIngressMaps struct {
	ArpTable      *ebpf.Map `ebpf:"arp_table"`
	Fdb           *ebpf.Map `ebpf:"fdb"`
	HostIface     *ebpf.Map `ebpf:"host_iface"`
	IfindexSubnet *ebpf.Map `ebpf:"ifindex_subnet"`
	VxlanIfindex  *ebpf.Map `ebpf:"vxlan_ifindex"`
}

func (m *VxlanIngressMaps) Close() error {
	return _VxlanIngressClose(
		m.ArpTable,
		m.Fdb,
		m.HostIface,
		m.IfindexSubnet,
		m.VxlanIfindex,
	)
}

// VxlanIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanIngressVariables struct {
}

// VxlanIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanIngressPrograms struct {
	TcVxlanIngressEntry *ebpf.Program `ebpf:"tc_vxlan_ingress_entry"`
}

func (p *VxlanIngressPrograms) Close() error {
	return _VxlanIngressClose(
		p.TcVxlanIngressEntry,
	)
}

func _VxlanIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed vxlaningress_bpfeb.o
var _VxlanIngressBytes []byte
