// debug.proto carries the operational debug API kubectl-juneau
// uses to drive a trace session: it streams ringbuf events from one
// daemon, exchanges learned tuples between daemons, and lets kubectl
// inject probes when active probing is requested.
//
// The service is intentionally distinct from CNI (cni.proto) — CNI
// is wired into the kubelet boot sequence and must stay frozen while
// the trace API is operator-facing and may evolve more frequently.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: pkg/debugpb/debug.proto

package debugpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InjectProbeStrategy int32

const (
	InjectProbeStrategy_INJECT_PROBE_STRATEGY_UNSPECIFIED InjectProbeStrategy = 0
	// POD_EXEC: kubectl will exec into the source Pod itself; the
	// daemon does not generate a packet. Reported here for
	// completeness — kubectl falls back to this if the daemon does
	// not support a more privileged strategy.
	InjectProbeStrategy_INJECT_PROBE_STRATEGY_POD_EXEC InjectProbeStrategy = 1
	// DAEMON_NETNS: daemon enters the source Pod's netns and sends
	// from there. Most privileged option; guarded by capability.
	InjectProbeStrategy_INJECT_PROBE_STRATEGY_DAEMON_NETNS InjectProbeStrategy = 2
	// DAEMON_HOST: daemon sends from the host netns. Used for
	// node/underlay debugging.
	InjectProbeStrategy_INJECT_PROBE_STRATEGY_DAEMON_HOST InjectProbeStrategy = 3
)

// Enum value maps for InjectProbeStrategy.
var (
	InjectProbeStrategy_name = map[int32]string{
		0: "INJECT_PROBE_STRATEGY_UNSPECIFIED",
		1: "INJECT_PROBE_STRATEGY_POD_EXEC",
		2: "INJECT_PROBE_STRATEGY_DAEMON_NETNS",
		3: "INJECT_PROBE_STRATEGY_DAEMON_HOST",
	}
	InjectProbeStrategy_value = map[string]int32{
		"INJECT_PROBE_STRATEGY_UNSPECIFIED":  0,
		"INJECT_PROBE_STRATEGY_POD_EXEC":     1,
		"INJECT_PROBE_STRATEGY_DAEMON_NETNS": 2,
		"INJECT_PROBE_STRATEGY_DAEMON_HOST":  3,
	}
)

func (x InjectProbeStrategy) Enum() *InjectProbeStrategy {
	p := new(InjectProbeStrategy)
	*p = x
	return p
}

func (x InjectProbeStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InjectProbeStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[0].Descriptor()
}

func (InjectProbeStrategy) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[0]
}

func (x InjectProbeStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InjectProbeStrategy.Descriptor instead.
func (InjectProbeStrategy) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{0}
}

type TraceDirection int32

const (
	TraceDirection_TRACE_DIRECTION_UNSPECIFIED TraceDirection = 0
	TraceDirection_TRACE_DIRECTION_REQUEST     TraceDirection = 1
	TraceDirection_TRACE_DIRECTION_REPLY       TraceDirection = 2
)

// Enum value maps for TraceDirection.
var (
	TraceDirection_name = map[int32]string{
		0: "TRACE_DIRECTION_UNSPECIFIED",
		1: "TRACE_DIRECTION_REQUEST",
		2: "TRACE_DIRECTION_REPLY",
	}
	TraceDirection_value = map[string]int32{
		"TRACE_DIRECTION_UNSPECIFIED": 0,
		"TRACE_DIRECTION_REQUEST":     1,
		"TRACE_DIRECTION_REPLY":       2,
	}
)

func (x TraceDirection) Enum() *TraceDirection {
	p := new(TraceDirection)
	*p = x
	return p
}

func (x TraceDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[1].Descriptor()
}

func (TraceDirection) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[1]
}

func (x TraceDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceDirection.Descriptor instead.
func (TraceDirection) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{1}
}

type TupleScope int32

const (
	TupleScope_TUPLE_SCOPE_UNSPECIFIED TupleScope = 0
	TupleScope_TUPLE_SCOPE_HOST        TupleScope = 1
	TupleScope_TUPLE_SCOPE_VPC         TupleScope = 2
)

// Enum value maps for TupleScope.
var (
	TupleScope_name = map[int32]string{
		0: "TUPLE_SCOPE_UNSPECIFIED",
		1: "TUPLE_SCOPE_HOST",
		2: "TUPLE_SCOPE_VPC",
	}
	TupleScope_value = map[string]int32{
		"TUPLE_SCOPE_UNSPECIFIED": 0,
		"TUPLE_SCOPE_HOST":        1,
		"TUPLE_SCOPE_VPC":         2,
	}
)

func (x TupleScope) Enum() *TupleScope {
	p := new(TupleScope)
	*p = x
	return p
}

func (x TupleScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TupleScope) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[2].Descriptor()
}

func (TupleScope) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[2]
}

func (x TupleScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TupleScope.Descriptor instead.
func (TupleScope) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{2}
}

type TraceProtocol int32

const (
	TraceProtocol_TRACE_PROTOCOL_UNSPECIFIED TraceProtocol = 0
	TraceProtocol_TRACE_PROTOCOL_TCP         TraceProtocol = 1
	TraceProtocol_TRACE_PROTOCOL_UDP         TraceProtocol = 2
	TraceProtocol_TRACE_PROTOCOL_ICMP        TraceProtocol = 3
)

// Enum value maps for TraceProtocol.
var (
	TraceProtocol_name = map[int32]string{
		0: "TRACE_PROTOCOL_UNSPECIFIED",
		1: "TRACE_PROTOCOL_TCP",
		2: "TRACE_PROTOCOL_UDP",
		3: "TRACE_PROTOCOL_ICMP",
	}
	TraceProtocol_value = map[string]int32{
		"TRACE_PROTOCOL_UNSPECIFIED": 0,
		"TRACE_PROTOCOL_TCP":         1,
		"TRACE_PROTOCOL_UDP":         2,
		"TRACE_PROTOCOL_ICMP":        3,
	}
)

func (x TraceProtocol) Enum() *TraceProtocol {
	p := new(TraceProtocol)
	*p = x
	return p
}

func (x TraceProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[3].Descriptor()
}

func (TraceProtocol) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[3]
}

func (x TraceProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceProtocol.Descriptor instead.
func (TraceProtocol) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{3}
}

type TraceHook int32

const (
	TraceHook_TRACE_HOOK_UNSPECIFIED   TraceHook = 0
	TraceHook_TRACE_HOOK_POD_EGRESS    TraceHook = 1
	TraceHook_TRACE_HOOK_POD_INGRESS   TraceHook = 2
	TraceHook_TRACE_HOOK_VXLAN_INGRESS TraceHook = 3
	TraceHook_TRACE_HOOK_NODE_INGRESS  TraceHook = 4
)

// Enum value maps for TraceHook.
var (
	TraceHook_name = map[int32]string{
		0: "TRACE_HOOK_UNSPECIFIED",
		1: "TRACE_HOOK_POD_EGRESS",
		2: "TRACE_HOOK_POD_INGRESS",
		3: "TRACE_HOOK_VXLAN_INGRESS",
		4: "TRACE_HOOK_NODE_INGRESS",
	}
	TraceHook_value = map[string]int32{
		"TRACE_HOOK_UNSPECIFIED":   0,
		"TRACE_HOOK_POD_EGRESS":    1,
		"TRACE_HOOK_POD_INGRESS":   2,
		"TRACE_HOOK_VXLAN_INGRESS": 3,
		"TRACE_HOOK_NODE_INGRESS":  4,
	}
)

func (x TraceHook) Enum() *TraceHook {
	p := new(TraceHook)
	*p = x
	return p
}

func (x TraceHook) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceHook) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[4].Descriptor()
}

func (TraceHook) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[4]
}

func (x TraceHook) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceHook.Descriptor instead.
func (TraceHook) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{4}
}

type TraceVerdict int32

const (
	TraceVerdict_TRACE_VERDICT_UNSPECIFIED TraceVerdict = 0
	TraceVerdict_TRACE_VERDICT_OK          TraceVerdict = 1
	TraceVerdict_TRACE_VERDICT_DROP        TraceVerdict = 2
	TraceVerdict_TRACE_VERDICT_REDIRECT    TraceVerdict = 3
)

// Enum value maps for TraceVerdict.
var (
	TraceVerdict_name = map[int32]string{
		0: "TRACE_VERDICT_UNSPECIFIED",
		1: "TRACE_VERDICT_OK",
		2: "TRACE_VERDICT_DROP",
		3: "TRACE_VERDICT_REDIRECT",
	}
	TraceVerdict_value = map[string]int32{
		"TRACE_VERDICT_UNSPECIFIED": 0,
		"TRACE_VERDICT_OK":          1,
		"TRACE_VERDICT_DROP":        2,
		"TRACE_VERDICT_REDIRECT":    3,
	}
)

func (x TraceVerdict) Enum() *TraceVerdict {
	p := new(TraceVerdict)
	*p = x
	return p
}

func (x TraceVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[5].Descriptor()
}

func (TraceVerdict) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[5]
}

func (x TraceVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceVerdict.Descriptor instead.
func (TraceVerdict) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{5}
}

type TraceEventReason int32

const (
	TraceEventReason_TRACE_EVENT_REASON_UNSPECIFIED              TraceEventReason = 0
	TraceEventReason_TRACE_EVENT_REASON_ENTER_POD_EGRESS         TraceEventReason = 100
	TraceEventReason_TRACE_EVENT_REASON_ENTER_POD_INGRESS        TraceEventReason = 101
	TraceEventReason_TRACE_EVENT_REASON_ENTER_VXLAN_INGRESS      TraceEventReason = 102
	TraceEventReason_TRACE_EVENT_REASON_ENTER_NODE_INGRESS       TraceEventReason = 103
	TraceEventReason_TRACE_EVENT_REASON_MISS_IFINDEX_SUBNET      TraceEventReason = 200
	TraceEventReason_TRACE_EVENT_REASON_MISS_SUBNET              TraceEventReason = 201
	TraceEventReason_TRACE_EVENT_REASON_MISS_FIB_TABLE           TraceEventReason = 202
	TraceEventReason_TRACE_EVENT_REASON_MISS_FIB_ROUTE           TraceEventReason = 203
	TraceEventReason_TRACE_EVENT_REASON_MISS_ARP                 TraceEventReason = 204
	TraceEventReason_TRACE_EVENT_REASON_MISS_FDB                 TraceEventReason = 205
	TraceEventReason_TRACE_EVENT_REASON_MISS_SERVICE             TraceEventReason = 206
	TraceEventReason_TRACE_EVENT_REASON_MISS_BACKEND             TraceEventReason = 207
	TraceEventReason_TRACE_EVENT_REASON_MISS_CONNTRACK           TraceEventReason = 208
	TraceEventReason_TRACE_EVENT_REASON_MISS_TGW_TABLE           TraceEventReason = 209
	TraceEventReason_TRACE_EVENT_REASON_MISS_TGW_ROUTE           TraceEventReason = 210
	TraceEventReason_TRACE_EVENT_REASON_POLICY_ACL_PASS          TraceEventReason = 300
	TraceEventReason_TRACE_EVENT_REASON_POLICY_ACL_DROP          TraceEventReason = 301
	TraceEventReason_TRACE_EVENT_REASON_POLICY_SG_PASS           TraceEventReason = 302
	TraceEventReason_TRACE_EVENT_REASON_POLICY_SG_DROP           TraceEventReason = 303
	TraceEventReason_TRACE_EVENT_REASON_SERVICE_LOOKUP_HIT       TraceEventReason = 400
	TraceEventReason_TRACE_EVENT_REASON_SERVICE_BACKEND_SELECTED TraceEventReason = 401
	TraceEventReason_TRACE_EVENT_REASON_DNAT_APPLIED             TraceEventReason = 402
	TraceEventReason_TRACE_EVENT_REASON_SNAT_APPLIED             TraceEventReason = 403
	TraceEventReason_TRACE_EVENT_REASON_NAPT_ALLOCATED           TraceEventReason = 404
	TraceEventReason_TRACE_EVENT_REASON_REVERSE_NAT_APPLIED      TraceEventReason = 405
	TraceEventReason_TRACE_EVENT_REASON_REDIRECT_IFINDEX         TraceEventReason = 500
	TraceEventReason_TRACE_EVENT_REASON_REDIRECT_VXLAN           TraceEventReason = 501
	TraceEventReason_TRACE_EVENT_REASON_PASS_KERNEL              TraceEventReason = 502
	TraceEventReason_TRACE_EVENT_REASON_DROP_SHOT                TraceEventReason = 503
	TraceEventReason_TRACE_EVENT_REASON_DROP_BLACKHOLE           TraceEventReason = 504
)

// Enum value maps for TraceEventReason.
var (
	TraceEventReason_name = map[int32]string{
		0:   "TRACE_EVENT_REASON_UNSPECIFIED",
		100: "TRACE_EVENT_REASON_ENTER_POD_EGRESS",
		101: "TRACE_EVENT_REASON_ENTER_POD_INGRESS",
		102: "TRACE_EVENT_REASON_ENTER_VXLAN_INGRESS",
		103: "TRACE_EVENT_REASON_ENTER_NODE_INGRESS",
		200: "TRACE_EVENT_REASON_MISS_IFINDEX_SUBNET",
		201: "TRACE_EVENT_REASON_MISS_SUBNET",
		202: "TRACE_EVENT_REASON_MISS_FIB_TABLE",
		203: "TRACE_EVENT_REASON_MISS_FIB_ROUTE",
		204: "TRACE_EVENT_REASON_MISS_ARP",
		205: "TRACE_EVENT_REASON_MISS_FDB",
		206: "TRACE_EVENT_REASON_MISS_SERVICE",
		207: "TRACE_EVENT_REASON_MISS_BACKEND",
		208: "TRACE_EVENT_REASON_MISS_CONNTRACK",
		209: "TRACE_EVENT_REASON_MISS_TGW_TABLE",
		210: "TRACE_EVENT_REASON_MISS_TGW_ROUTE",
		300: "TRACE_EVENT_REASON_POLICY_ACL_PASS",
		301: "TRACE_EVENT_REASON_POLICY_ACL_DROP",
		302: "TRACE_EVENT_REASON_POLICY_SG_PASS",
		303: "TRACE_EVENT_REASON_POLICY_SG_DROP",
		400: "TRACE_EVENT_REASON_SERVICE_LOOKUP_HIT",
		401: "TRACE_EVENT_REASON_SERVICE_BACKEND_SELECTED",
		402: "TRACE_EVENT_REASON_DNAT_APPLIED",
		403: "TRACE_EVENT_REASON_SNAT_APPLIED",
		404: "TRACE_EVENT_REASON_NAPT_ALLOCATED",
		405: "TRACE_EVENT_REASON_REVERSE_NAT_APPLIED",
		500: "TRACE_EVENT_REASON_REDIRECT_IFINDEX",
		501: "TRACE_EVENT_REASON_REDIRECT_VXLAN",
		502: "TRACE_EVENT_REASON_PASS_KERNEL",
		503: "TRACE_EVENT_REASON_DROP_SHOT",
		504: "TRACE_EVENT_REASON_DROP_BLACKHOLE",
	}
	TraceEventReason_value = map[string]int32{
		"TRACE_EVENT_REASON_UNSPECIFIED":              0,
		"TRACE_EVENT_REASON_ENTER_POD_EGRESS":         100,
		"TRACE_EVENT_REASON_ENTER_POD_INGRESS":        101,
		"TRACE_EVENT_REASON_ENTER_VXLAN_INGRESS":      102,
		"TRACE_EVENT_REASON_ENTER_NODE_INGRESS":       103,
		"TRACE_EVENT_REASON_MISS_IFINDEX_SUBNET":      200,
		"TRACE_EVENT_REASON_MISS_SUBNET":              201,
		"TRACE_EVENT_REASON_MISS_FIB_TABLE":           202,
		"TRACE_EVENT_REASON_MISS_FIB_ROUTE":           203,
		"TRACE_EVENT_REASON_MISS_ARP":                 204,
		"TRACE_EVENT_REASON_MISS_FDB":                 205,
		"TRACE_EVENT_REASON_MISS_SERVICE":             206,
		"TRACE_EVENT_REASON_MISS_BACKEND":             207,
		"TRACE_EVENT_REASON_MISS_CONNTRACK":           208,
		"TRACE_EVENT_REASON_MISS_TGW_TABLE":           209,
		"TRACE_EVENT_REASON_MISS_TGW_ROUTE":           210,
		"TRACE_EVENT_REASON_POLICY_ACL_PASS":          300,
		"TRACE_EVENT_REASON_POLICY_ACL_DROP":          301,
		"TRACE_EVENT_REASON_POLICY_SG_PASS":           302,
		"TRACE_EVENT_REASON_POLICY_SG_DROP":           303,
		"TRACE_EVENT_REASON_SERVICE_LOOKUP_HIT":       400,
		"TRACE_EVENT_REASON_SERVICE_BACKEND_SELECTED": 401,
		"TRACE_EVENT_REASON_DNAT_APPLIED":             402,
		"TRACE_EVENT_REASON_SNAT_APPLIED":             403,
		"TRACE_EVENT_REASON_NAPT_ALLOCATED":           404,
		"TRACE_EVENT_REASON_REVERSE_NAT_APPLIED":      405,
		"TRACE_EVENT_REASON_REDIRECT_IFINDEX":         500,
		"TRACE_EVENT_REASON_REDIRECT_VXLAN":           501,
		"TRACE_EVENT_REASON_PASS_KERNEL":              502,
		"TRACE_EVENT_REASON_DROP_SHOT":                503,
		"TRACE_EVENT_REASON_DROP_BLACKHOLE":           504,
	}
)

func (x TraceEventReason) Enum() *TraceEventReason {
	p := new(TraceEventReason)
	*p = x
	return p
}

func (x TraceEventReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceEventReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_debugpb_debug_proto_enumTypes[6].Descriptor()
}

func (TraceEventReason) Type() protoreflect.EnumType {
	return &file_pkg_debugpb_debug_proto_enumTypes[6]
}

func (x TraceEventReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceEventReason.Descriptor instead.
func (TraceEventReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{6}
}

type WatchTraceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trace_ids the client wants events for. Empty selects every
	// session known to this node — daemons may rate-limit or refuse
	// unbounded subscriptions in production.
	TraceIds []uint32 `protobuf:"varint,1,rep,packed,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`
	// buffer_hint advises the per-stream channel size. 0 lets the
	// daemon pick a sane default.
	BufferHint    uint32 `protobuf:"varint,2,opt,name=buffer_hint,json=bufferHint,proto3" json:"buffer_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTraceRequest) Reset() {
	*x = WatchTraceRequest{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTraceRequest) ProtoMessage() {}

func (x *WatchTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTraceRequest.ProtoReflect.Descriptor instead.
func (*WatchTraceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{0}
}

func (x *WatchTraceRequest) GetTraceIds() []uint32 {
	if x != nil {
		return x.TraceIds
	}
	return nil
}

func (x *WatchTraceRequest) GetBufferHint() uint32 {
	if x != nil {
		return x.BufferHint
	}
	return 0
}

type GetTraceSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       uint32                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceSnapshotRequest) Reset() {
	*x = GetTraceSnapshotRequest{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceSnapshotRequest) ProtoMessage() {}

func (x *GetTraceSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetTraceSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{1}
}

func (x *GetTraceSnapshotRequest) GetTraceId() uint32 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

type TraceSnapshot struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TraceId  uint32                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	NodeName string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// tuples currently programmed in this node's BPF trace_tuple_map
	// for the session.
	Tuples []*TraceTuple `protobuf:"bytes,3,rep,name=tuples,proto3" json:"tuples,omitempty"`
	// recent_events is a bounded backlog. Daemons cap it to keep memory
	// pressure predictable; kubectl uses it only to fill in the gap
	// between session start and stream attach.
	RecentEvents  []*TraceEvent `protobuf:"bytes,4,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	DroppedEvents uint64        `protobuf:"varint,5,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceSnapshot) Reset() {
	*x = TraceSnapshot{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSnapshot) ProtoMessage() {}

func (x *TraceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSnapshot.ProtoReflect.Descriptor instead.
func (*TraceSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{2}
}

func (x *TraceSnapshot) GetTraceId() uint32 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *TraceSnapshot) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TraceSnapshot) GetTuples() []*TraceTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *TraceSnapshot) GetRecentEvents() []*TraceEvent {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

func (x *TraceSnapshot) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

type InjectProbeRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TraceId uint32                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// strategy picks how the daemon synthesises the packet. The values
	// are negotiated between kubectl and the daemon via discovery; new
	// strategies extend the enum without breaking older daemons.
	Strategy InjectProbeStrategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=debug.v1.InjectProbeStrategy" json:"strategy,omitempty"`
	Tuple    *TraceTuple         `protobuf:"bytes,3,opt,name=tuple,proto3" json:"tuple,omitempty"`
	// payload_bytes is an optional probe payload (e.g. a trace token).
	PayloadBytes  []byte `protobuf:"bytes,4,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectProbeRequest) Reset() {
	*x = InjectProbeRequest{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectProbeRequest) ProtoMessage() {}

func (x *InjectProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectProbeRequest.ProtoReflect.Descriptor instead.
func (*InjectProbeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{3}
}

func (x *InjectProbeRequest) GetTraceId() uint32 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *InjectProbeRequest) GetStrategy() InjectProbeStrategy {
	if x != nil {
		return x.Strategy
	}
	return InjectProbeStrategy_INJECT_PROBE_STRATEGY_UNSPECIFIED
}

func (x *InjectProbeRequest) GetTuple() *TraceTuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

func (x *InjectProbeRequest) GetPayloadBytes() []byte {
	if x != nil {
		return x.PayloadBytes
	}
	return nil
}

type InjectProbeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// packet_id is opaque; daemons return a value the client can
	// correlate with subsequent WatchTrace events if they encode it
	// into the probe payload.
	PacketId      uint64 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectProbeResponse) Reset() {
	*x = InjectProbeResponse{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectProbeResponse) ProtoMessage() {}

func (x *InjectProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectProbeResponse.ProtoReflect.Descriptor instead.
func (*InjectProbeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{4}
}

func (x *InjectProbeResponse) GetPacketId() uint64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

type LearnTupleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       uint32                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Tuple         *TraceTuple            `protobuf:"bytes,2,opt,name=tuple,proto3" json:"tuple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnTupleRequest) Reset() {
	*x = LearnTupleRequest{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnTupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnTupleRequest) ProtoMessage() {}

func (x *LearnTupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnTupleRequest.ProtoReflect.Descriptor instead.
func (*LearnTupleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{5}
}

func (x *LearnTupleRequest) GetTraceId() uint32 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *LearnTupleRequest) GetTuple() *TraceTuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

// TraceTuple mirrors juneau_trace_event's tuple representation in the
// CRD: a 5-tuple plus VPC scope. Numbers carry over to the BPF map
// keys verbatim.
type TraceTuple struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Scope    TupleScope             `protobuf:"varint,1,opt,name=scope,proto3,enum=debug.v1.TupleScope" json:"scope,omitempty"`
	VpcId    uint32                 `protobuf:"varint,2,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SrcIp    []byte                 `protobuf:"bytes,3,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"` // IPv4 in network byte order (4 bytes)
	DstIp    []byte                 `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort  uint32                 `protobuf:"varint,5,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"` // host byte order
	DstPort  uint32                 `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol TraceProtocol          `protobuf:"varint,7,opt,name=protocol,proto3,enum=debug.v1.TraceProtocol" json:"protocol,omitempty"`
	// direction is the leg this tuple belongs to. Programmed into
	// trace_tuple_map's value so events carry an authoritative
	// request/reply tag. Unspecified is treated as Request by daemons
	// (the common forward-continuation case for LearnTuple).
	Direction     TraceDirection `protobuf:"varint,8,opt,name=direction,proto3,enum=debug.v1.TraceDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceTuple) Reset() {
	*x = TraceTuple{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceTuple) ProtoMessage() {}

func (x *TraceTuple) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceTuple.ProtoReflect.Descriptor instead.
func (*TraceTuple) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{6}
}

func (x *TraceTuple) GetScope() TupleScope {
	if x != nil {
		return x.Scope
	}
	return TupleScope_TUPLE_SCOPE_UNSPECIFIED
}

func (x *TraceTuple) GetVpcId() uint32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

func (x *TraceTuple) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *TraceTuple) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *TraceTuple) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TraceTuple) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TraceTuple) GetProtocol() TraceProtocol {
	if x != nil {
		return x.Protocol
	}
	return TraceProtocol_TRACE_PROTOCOL_UNSPECIFIED
}

func (x *TraceTuple) GetDirection() TraceDirection {
	if x != nil {
		return x.Direction
	}
	return TraceDirection_TRACE_DIRECTION_UNSPECIFIED
}

// TraceEvent is the wire encoding of one ringbuf record after the
// daemon's decoder has translated raw fields. Stable across releases
// — append, never renumber. Numbers must match daemon/bpf/trace.h
// reason / hook / verdict constants so the userspace renderer can
// decode old captures from new daemons.
type TraceEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TraceId  uint32                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Reason   TraceEventReason       `protobuf:"varint,2,opt,name=reason,proto3,enum=debug.v1.TraceEventReason" json:"reason,omitempty"`
	Hook     TraceHook              `protobuf:"varint,3,opt,name=hook,proto3,enum=debug.v1.TraceHook" json:"hook,omitempty"`
	NodeName string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Ifindex  uint32                 `protobuf:"varint,5,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	VpcId    uint32                 `protobuf:"varint,6,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SubnetId uint32                 `protobuf:"varint,7,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// monotonic_ns is the bpf_ktime_get_ns timestamp on the daemon's
	// host. Cross-node ordering uses received_ns instead.
	MonotonicNs uint64 `protobuf:"varint,8,opt,name=monotonic_ns,json=monotonicNs,proto3" json:"monotonic_ns,omitempty"`
	// received_ns is the wallclock the daemon decoded the event,
	// expressed in unix nanoseconds.
	ReceivedNs  uint64        `protobuf:"varint,9,opt,name=received_ns,json=receivedNs,proto3" json:"received_ns,omitempty"`
	Protocol    TraceProtocol `protobuf:"varint,10,opt,name=protocol,proto3,enum=debug.v1.TraceProtocol" json:"protocol,omitempty"`
	Verdict     TraceVerdict  `protobuf:"varint,11,opt,name=verdict,proto3,enum=debug.v1.TraceVerdict" json:"verdict,omitempty"`
	Scope       TupleScope    `protobuf:"varint,12,opt,name=scope,proto3,enum=debug.v1.TupleScope" json:"scope,omitempty"`
	SrcIp       []byte        `protobuf:"bytes,13,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp       []byte        `protobuf:"bytes,14,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort     uint32        `protobuf:"varint,15,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort     uint32        `protobuf:"varint,16,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	HasAuxTuple bool          `protobuf:"varint,17,opt,name=has_aux_tuple,json=hasAuxTuple,proto3" json:"has_aux_tuple,omitempty"`
	AuxSrcIp    []byte        `protobuf:"bytes,18,opt,name=aux_src_ip,json=auxSrcIp,proto3" json:"aux_src_ip,omitempty"`
	AuxDstIp    []byte        `protobuf:"bytes,19,opt,name=aux_dst_ip,json=auxDstIp,proto3" json:"aux_dst_ip,omitempty"`
	AuxSrcPort  uint32        `protobuf:"varint,20,opt,name=aux_src_port,json=auxSrcPort,proto3" json:"aux_src_port,omitempty"`
	AuxDstPort  uint32        `protobuf:"varint,21,opt,name=aux_dst_port,json=auxDstPort,proto3" json:"aux_dst_port,omitempty"`
	Aux1        uint32        `protobuf:"varint,22,opt,name=aux1,proto3" json:"aux1,omitempty"`
	Aux2        uint32        `protobuf:"varint,23,opt,name=aux2,proto3" json:"aux2,omitempty"`
	// direction is the authoritative request/reply tag carried on the
	// matched trace_tuple_map entry. kubectl renders it directly instead
	// of inferring the leg from address orientation.
	Direction     TraceDirection `protobuf:"varint,24,opt,name=direction,proto3,enum=debug.v1.TraceDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{7}
}

func (x *TraceEvent) GetTraceId() uint32 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *TraceEvent) GetReason() TraceEventReason {
	if x != nil {
		return x.Reason
	}
	return TraceEventReason_TRACE_EVENT_REASON_UNSPECIFIED
}

func (x *TraceEvent) GetHook() TraceHook {
	if x != nil {
		return x.Hook
	}
	return TraceHook_TRACE_HOOK_UNSPECIFIED
}

func (x *TraceEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TraceEvent) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

func (x *TraceEvent) GetVpcId() uint32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

func (x *TraceEvent) GetSubnetId() uint32 {
	if x != nil {
		return x.SubnetId
	}
	return 0
}

func (x *TraceEvent) GetMonotonicNs() uint64 {
	if x != nil {
		return x.MonotonicNs
	}
	return 0
}

func (x *TraceEvent) GetReceivedNs() uint64 {
	if x != nil {
		return x.ReceivedNs
	}
	return 0
}

func (x *TraceEvent) GetProtocol() TraceProtocol {
	if x != nil {
		return x.Protocol
	}
	return TraceProtocol_TRACE_PROTOCOL_UNSPECIFIED
}

func (x *TraceEvent) GetVerdict() TraceVerdict {
	if x != nil {
		return x.Verdict
	}
	return TraceVerdict_TRACE_VERDICT_UNSPECIFIED
}

func (x *TraceEvent) GetScope() TupleScope {
	if x != nil {
		return x.Scope
	}
	return TupleScope_TUPLE_SCOPE_UNSPECIFIED
}

func (x *TraceEvent) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *TraceEvent) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *TraceEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TraceEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TraceEvent) GetHasAuxTuple() bool {
	if x != nil {
		return x.HasAuxTuple
	}
	return false
}

func (x *TraceEvent) GetAuxSrcIp() []byte {
	if x != nil {
		return x.AuxSrcIp
	}
	return nil
}

func (x *TraceEvent) GetAuxDstIp() []byte {
	if x != nil {
		return x.AuxDstIp
	}
	return nil
}

func (x *TraceEvent) GetAuxSrcPort() uint32 {
	if x != nil {
		return x.AuxSrcPort
	}
	return 0
}

func (x *TraceEvent) GetAuxDstPort() uint32 {
	if x != nil {
		return x.AuxDstPort
	}
	return 0
}

func (x *TraceEvent) GetAux1() uint32 {
	if x != nil {
		return x.Aux1
	}
	return 0
}

func (x *TraceEvent) GetAux2() uint32 {
	if x != nil {
		return x.Aux2
	}
	return 0
}

func (x *TraceEvent) GetDirection() TraceDirection {
	if x != nil {
		return x.Direction
	}
	return TraceDirection_TRACE_DIRECTION_UNSPECIFIED
}

// BPFMapField is one named element of a key or value tuple. Exactly one
// of u64/ipv4/mac/label/raw should be set; flags is supplemental for
// bitmask fields and is empty for plain values.
type BPFMapField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*BPFMapField_U64
	//	*BPFMapField_Ipv4
	//	*BPFMapField_Mac
	//	*BPFMapField_Label
	//	*BPFMapField_Raw
	Value isBPFMapField_Value `protobuf_oneof:"value"`
	// flags is the human-readable expansion of bitmask fields.
	// Populated alongside u64; clients that ignore it still see the
	// numeric value. Empty for non-flag fields.
	Flags         []string `protobuf:"bytes,20,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BPFMapField) Reset() {
	*x = BPFMapField{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BPFMapField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPFMapField) ProtoMessage() {}

func (x *BPFMapField) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPFMapField.ProtoReflect.Descriptor instead.
func (*BPFMapField) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{8}
}

func (x *BPFMapField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BPFMapField) GetValue() isBPFMapField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BPFMapField) GetU64() uint64 {
	if x != nil {
		if x, ok := x.Value.(*BPFMapField_U64); ok {
			return x.U64
		}
	}
	return 0
}

func (x *BPFMapField) GetIpv4() string {
	if x != nil {
		if x, ok := x.Value.(*BPFMapField_Ipv4); ok {
			return x.Ipv4
		}
	}
	return ""
}

func (x *BPFMapField) GetMac() string {
	if x != nil {
		if x, ok := x.Value.(*BPFMapField_Mac); ok {
			return x.Mac
		}
	}
	return ""
}

func (x *BPFMapField) GetLabel() string {
	if x != nil {
		if x, ok := x.Value.(*BPFMapField_Label); ok {
			return x.Label
		}
	}
	return ""
}

func (x *BPFMapField) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Value.(*BPFMapField_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *BPFMapField) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type isBPFMapField_Value interface {
	isBPFMapField_Value()
}

type BPFMapField_U64 struct {
	U64 uint64 `protobuf:"varint,10,opt,name=u64,proto3,oneof"` // generic numeric (u8/u16/u32/u64)
}

type BPFMapField_Ipv4 struct {
	Ipv4 string `protobuf:"bytes,11,opt,name=ipv4,proto3,oneof"` // dotted-quad (decoder normalises NBO/HBO)
}

type BPFMapField_Mac struct {
	Mac string `protobuf:"bytes,12,opt,name=mac,proto3,oneof"` // colon-hex
}

type BPFMapField_Label struct {
	Label string `protobuf:"bytes,13,opt,name=label,proto3,oneof"` // resolved enum / sentinel ("CT_ACTION_DNAT")
}

type BPFMapField_Raw struct {
	Raw []byte `protobuf:"bytes,14,opt,name=raw,proto3,oneof"` // fallback for unknown shapes
}

func (*BPFMapField_U64) isBPFMapField_Value() {}

func (*BPFMapField_Ipv4) isBPFMapField_Value() {}

func (*BPFMapField_Mac) isBPFMapField_Value() {}

func (*BPFMapField_Label) isBPFMapField_Value() {}

func (*BPFMapField_Raw) isBPFMapField_Value() {}

// BPFMapFieldSchema describes one field's name and rendering hint.
// `type` is a stable identifier ("u32", "ipv4", "mac", "enum:ct_action",
// "flags:svc_flag") that the daemon also uses internally; clients may
// use it to drive table column formatting.
type BPFMapFieldSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BPFMapFieldSchema) Reset() {
	*x = BPFMapFieldSchema{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BPFMapFieldSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPFMapFieldSchema) ProtoMessage() {}

func (x *BPFMapFieldSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPFMapFieldSchema.ProtoReflect.Descriptor instead.
func (*BPFMapFieldSchema) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{9}
}

func (x *BPFMapFieldSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BPFMapFieldSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BPFMapFieldSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// BPFMapSchema is the per-map descriptor returned by ListBPFMaps.
// kind mirrors cilium/ebpf MapType.String() (HASH, LRU_HASH, LPM_TRIE,
// HASH_OF_MAPS, ARRAY) so kubectl can format it as-is.
type BPFMapSchema struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind        string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	MaxEntries  uint32                 `protobuf:"varint,3,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	KeySchema   []*BPFMapFieldSchema   `protobuf:"bytes,4,rep,name=key_schema,json=keySchema,proto3" json:"key_schema,omitempty"`
	ValueSchema []*BPFMapFieldSchema   `protobuf:"bytes,5,rep,name=value_schema,json=valueSchema,proto3" json:"value_schema,omitempty"`
	// requires_inner_key marks HASH_OF_MAPS-style maps. DumpBPFMap on
	// such a map without an inner_key returns the outer keys only.
	RequiresInnerKey bool `protobuf:"varint,6,opt,name=requires_inner_key,json=requiresInnerKey,proto3" json:"requires_inner_key,omitempty"`
	// inner_key_schema is populated only when requires_inner_key=true.
	// Mirrors the inner map's key schema so kubectl can validate
	// --inner-key flags up front.
	InnerKeySchema []*BPFMapFieldSchema `protobuf:"bytes,7,rep,name=inner_key_schema,json=innerKeySchema,proto3" json:"inner_key_schema,omitempty"`
	// inner_value_schema mirrors the inner map's value schema (only set
	// when requires_inner_key=true).
	InnerValueSchema []*BPFMapFieldSchema `protobuf:"bytes,8,rep,name=inner_value_schema,json=innerValueSchema,proto3" json:"inner_value_schema,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BPFMapSchema) Reset() {
	*x = BPFMapSchema{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BPFMapSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPFMapSchema) ProtoMessage() {}

func (x *BPFMapSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPFMapSchema.ProtoReflect.Descriptor instead.
func (*BPFMapSchema) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{10}
}

func (x *BPFMapSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BPFMapSchema) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BPFMapSchema) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *BPFMapSchema) GetKeySchema() []*BPFMapFieldSchema {
	if x != nil {
		return x.KeySchema
	}
	return nil
}

func (x *BPFMapSchema) GetValueSchema() []*BPFMapFieldSchema {
	if x != nil {
		return x.ValueSchema
	}
	return nil
}

func (x *BPFMapSchema) GetRequiresInnerKey() bool {
	if x != nil {
		return x.RequiresInnerKey
	}
	return false
}

func (x *BPFMapSchema) GetInnerKeySchema() []*BPFMapFieldSchema {
	if x != nil {
		return x.InnerKeySchema
	}
	return nil
}

func (x *BPFMapSchema) GetInnerValueSchema() []*BPFMapFieldSchema {
	if x != nil {
		return x.InnerValueSchema
	}
	return nil
}

type ListBPFMapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBPFMapsRequest) Reset() {
	*x = ListBPFMapsRequest{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBPFMapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBPFMapsRequest) ProtoMessage() {}

func (x *ListBPFMapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBPFMapsRequest.ProtoReflect.Descriptor instead.
func (*ListBPFMapsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{11}
}

type ListBPFMapsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maps          []*BPFMapSchema        `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBPFMapsResponse) Reset() {
	*x = ListBPFMapsResponse{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBPFMapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBPFMapsResponse) ProtoMessage() {}

func (x *ListBPFMapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBPFMapsResponse.ProtoReflect.Descriptor instead.
func (*ListBPFMapsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{12}
}

func (x *ListBPFMapsResponse) GetMaps() []*BPFMapSchema {
	if x != nil {
		return x.Maps
	}
	return nil
}

type DumpBPFMapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// key_filter constrains the dump to entries matching every named
	// field. Field names must reference the map's key_schema.
	KeyFilter []*BPFMapField `protobuf:"bytes,2,rep,name=key_filter,json=keyFilter,proto3" json:"key_filter,omitempty"`
	// inner_key picks the inner map for HASH_OF_MAPS dumps.
	InnerKey []*BPFMapField `protobuf:"bytes,3,rep,name=inner_key,json=innerKey,proto3" json:"inner_key,omitempty"`
	// limit caps the streamed entries; 0 means "use server default".
	// Servers may impose their own ceiling regardless.
	Limit         uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpBPFMapRequest) Reset() {
	*x = DumpBPFMapRequest{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpBPFMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpBPFMapRequest) ProtoMessage() {}

func (x *DumpBPFMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpBPFMapRequest.ProtoReflect.Descriptor instead.
func (*DumpBPFMapRequest) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{13}
}

func (x *DumpBPFMapRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DumpBPFMapRequest) GetKeyFilter() []*BPFMapField {
	if x != nil {
		return x.KeyFilter
	}
	return nil
}

func (x *DumpBPFMapRequest) GetInnerKey() []*BPFMapField {
	if x != nil {
		return x.InnerKey
	}
	return nil
}

func (x *DumpBPFMapRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BPFMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []*BPFMapField         `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	Value         []*BPFMapField         `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BPFMapEntry) Reset() {
	*x = BPFMapEntry{}
	mi := &file_pkg_debugpb_debug_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BPFMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPFMapEntry) ProtoMessage() {}

func (x *BPFMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_debugpb_debug_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPFMapEntry.ProtoReflect.Descriptor instead.
func (*BPFMapEntry) Descriptor() ([]byte, []int) {
	return file_pkg_debugpb_debug_proto_rawDescGZIP(), []int{14}
}

func (x *BPFMapEntry) GetKey() []*BPFMapField {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BPFMapEntry) GetValue() []*BPFMapField {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_pkg_debugpb_debug_proto protoreflect.FileDescriptor

const file_pkg_debugpb_debug_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/debugpb/debug.proto\x12\bdebug.v1\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\x11WatchTraceRequest\x12\x1b\n" +
	"\ttrace_ids\x18\x01 \x03(\rR\btraceIds\x12\x1f\n" +
	"\vbuffer_hint\x18\x02 \x01(\rR\n" +
	"bufferHint\"4\n" +
	"\x17GetTraceSnapshotRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\rR\atraceId\"\xd7\x01\n" +
	"\rTraceSnapshot\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\rR\atraceId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12,\n" +
	"\x06tuples\x18\x03 \x03(\v2\x14.debug.v1.TraceTupleR\x06tuples\x129\n" +
	"\rrecent_events\x18\x04 \x03(\v2\x14.debug.v1.TraceEventR\frecentEvents\x12%\n" +
	"\x0edropped_events\x18\x05 \x01(\x04R\rdroppedEvents\"\xbb\x01\n" +
	"\x12InjectProbeRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\rR\atraceId\x129\n" +
	"\bstrategy\x18\x02 \x01(\x0e2\x1d.debug.v1.InjectProbeStrategyR\bstrategy\x12*\n" +
	"\x05tuple\x18\x03 \x01(\v2\x14.debug.v1.TraceTupleR\x05tuple\x12#\n" +
	"\rpayload_bytes\x18\x04 \x01(\fR\fpayloadBytes\"2\n" +
	"\x13InjectProbeResponse\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\x04R\bpacketId\"Z\n" +
	"\x11LearnTupleRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\rR\atraceId\x12*\n" +
	"\x05tuple\x18\x02 \x01(\v2\x14.debug.v1.TraceTupleR\x05tuple\"\xa0\x02\n" +
	"\n" +
	"TraceTuple\x12*\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x14.debug.v1.TupleScopeR\x05scope\x12\x15\n" +
	"\x06vpc_id\x18\x02 \x01(\rR\x05vpcId\x12\x15\n" +
	"\x06src_ip\x18\x03 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x04 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x05 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\rR\adstPort\x123\n" +
	"\bprotocol\x18\a \x01(\x0e2\x17.debug.v1.TraceProtocolR\bprotocol\x126\n" +
	"\tdirection\x18\b \x01(\x0e2\x18.debug.v1.TraceDirectionR\tdirection\"\xae\x06\n" +
	"\n" +
	"TraceEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\rR\atraceId\x122\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1a.debug.v1.TraceEventReasonR\x06reason\x12'\n" +
	"\x04hook\x18\x03 \x01(\x0e2\x13.debug.v1.TraceHookR\x04hook\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x18\n" +
	"\aifindex\x18\x05 \x01(\rR\aifindex\x12\x15\n" +
	"\x06vpc_id\x18\x06 \x01(\rR\x05vpcId\x12\x1b\n" +
	"\tsubnet_id\x18\a \x01(\rR\bsubnetId\x12!\n" +
	"\fmonotonic_ns\x18\b \x01(\x04R\vmonotonicNs\x12\x1f\n" +
	"\vreceived_ns\x18\t \x01(\x04R\n" +
	"receivedNs\x123\n" +
	"\bprotocol\x18\n" +
	" \x01(\x0e2\x17.debug.v1.TraceProtocolR\bprotocol\x120\n" +
	"\averdict\x18\v \x01(\x0e2\x16.debug.v1.TraceVerdictR\averdict\x12*\n" +
	"\x05scope\x18\f \x01(\x0e2\x14.debug.v1.TupleScopeR\x05scope\x12\x15\n" +
	"\x06src_ip\x18\r \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x0e \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x0f \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x10 \x01(\rR\adstPort\x12\"\n" +
	"\rhas_aux_tuple\x18\x11 \x01(\bR\vhasAuxTuple\x12\x1c\n" +
	"\n" +
	"aux_src_ip\x18\x12 \x01(\fR\bauxSrcIp\x12\x1c\n" +
	"\n" +
	"aux_dst_ip\x18\x13 \x01(\fR\bauxDstIp\x12 \n" +
	"\faux_src_port\x18\x14 \x01(\rR\n" +
	"auxSrcPort\x12 \n" +
	"\faux_dst_port\x18\x15 \x01(\rR\n" +
	"auxDstPort\x12\x12\n" +
	"\x04aux1\x18\x16 \x01(\rR\x04aux1\x12\x12\n" +
	"\x04aux2\x18\x17 \x01(\rR\x04aux2\x126\n" +
	"\tdirection\x18\x18 \x01(\x0e2\x18.debug.v1.TraceDirectionR\tdirection\"\xaa\x01\n" +
	"\vBPFMapField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x03u64\x18\n" +
	" \x01(\x04H\x00R\x03u64\x12\x14\n" +
	"\x04ipv4\x18\v \x01(\tH\x00R\x04ipv4\x12\x12\n" +
	"\x03mac\x18\f \x01(\tH\x00R\x03mac\x12\x16\n" +
	"\x05label\x18\r \x01(\tH\x00R\x05label\x12\x12\n" +
	"\x03raw\x18\x0e \x01(\fH\x00R\x03raw\x12\x14\n" +
	"\x05flags\x18\x14 \x03(\tR\x05flagsB\a\n" +
	"\x05value\"]\n" +
	"\x11BPFMapFieldSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x93\x03\n" +
	"\fBPFMapSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vmax_entries\x18\x03 \x01(\rR\n" +
	"maxEntries\x12:\n" +
	"\n" +
	"key_schema\x18\x04 \x03(\v2\x1b.debug.v1.BPFMapFieldSchemaR\tkeySchema\x12>\n" +
	"\fvalue_schema\x18\x05 \x03(\v2\x1b.debug.v1.BPFMapFieldSchemaR\vvalueSchema\x12,\n" +
	"\x12requires_inner_key\x18\x06 \x01(\bR\x10requiresInnerKey\x12E\n" +
	"\x10inner_key_schema\x18\a \x03(\v2\x1b.debug.v1.BPFMapFieldSchemaR\x0einnerKeySchema\x12I\n" +
	"\x12inner_value_schema\x18\b \x03(\v2\x1b.debug.v1.BPFMapFieldSchemaR\x10innerValueSchema\"\x14\n" +
	"\x12ListBPFMapsRequest\"A\n" +
	"\x13ListBPFMapsResponse\x12*\n" +
	"\x04maps\x18\x01 \x03(\v2\x16.debug.v1.BPFMapSchemaR\x04maps\"\xa7\x01\n" +
	"\x11DumpBPFMapRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\n" +
	"key_filter\x18\x02 \x03(\v2\x15.debug.v1.BPFMapFieldR\tkeyFilter\x122\n" +
	"\tinner_key\x18\x03 \x03(\v2\x15.debug.v1.BPFMapFieldR\binnerKey\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"c\n" +
	"\vBPFMapEntry\x12'\n" +
	"\x03key\x18\x01 \x03(\v2\x15.debug.v1.BPFMapFieldR\x03key\x12+\n" +
	"\x05value\x18\x02 \x03(\v2\x15.debug.v1.BPFMapFieldR\x05value*\xaf\x01\n" +
	"\x13InjectProbeStrategy\x12%\n" +
	"!INJECT_PROBE_STRATEGY_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eINJECT_PROBE_STRATEGY_POD_EXEC\x10\x01\x12&\n" +
	"\"INJECT_PROBE_STRATEGY_DAEMON_NETNS\x10\x02\x12%\n" +
	"!INJECT_PROBE_STRATEGY_DAEMON_HOST\x10\x03*i\n" +
	"\x0eTraceDirection\x12\x1f\n" +
	"\x1bTRACE_DIRECTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRACE_DIRECTION_REQUEST\x10\x01\x12\x19\n" +
	"\x15TRACE_DIRECTION_REPLY\x10\x02*T\n" +
	"\n" +
	"TupleScope\x12\x1b\n" +
	"\x17TUPLE_SCOPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TUPLE_SCOPE_HOST\x10\x01\x12\x13\n" +
	"\x0fTUPLE_SCOPE_VPC\x10\x02*x\n" +
	"\rTraceProtocol\x12\x1e\n" +
	"\x1aTRACE_PROTOCOL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRACE_PROTOCOL_TCP\x10\x01\x12\x16\n" +
	"\x12TRACE_PROTOCOL_UDP\x10\x02\x12\x17\n" +
	"\x13TRACE_PROTOCOL_ICMP\x10\x03*\x99\x01\n" +
	"\tTraceHook\x12\x1a\n" +
	"\x16TRACE_HOOK_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRACE_HOOK_POD_EGRESS\x10\x01\x12\x1a\n" +
	"\x16TRACE_HOOK_POD_INGRESS\x10\x02\x12\x1c\n" +
	"\x18TRACE_HOOK_VXLAN_INGRESS\x10\x03\x12\x1b\n" +
	"\x17TRACE_HOOK_NODE_INGRESS\x10\x04*w\n" +
	"\fTraceVerdict\x12\x1d\n" +
	"\x19TRACE_VERDICT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TRACE_VERDICT_OK\x10\x01\x12\x16\n" +
	"\x12TRACE_VERDICT_DROP\x10\x02\x12\x1a\n" +
	"\x16TRACE_VERDICT_REDIRECT\x10\x03*\xed\t\n" +
	"\x10TraceEventReason\x12\"\n" +
	"\x1eTRACE_EVENT_REASON_UNSPECIFIED\x10\x00\x12'\n" +
	"#TRACE_EVENT_REASON_ENTER_POD_EGRESS\x10d\x12(\n" +
	"$TRACE_EVENT_REASON_ENTER_POD_INGRESS\x10e\x12*\n" +
	"&TRACE_EVENT_REASON_ENTER_VXLAN_INGRESS\x10f\x12)\n" +
	"%TRACE_EVENT_REASON_ENTER_NODE_INGRESS\x10g\x12+\n" +
	"&TRACE_EVENT_REASON_MISS_IFINDEX_SUBNET\x10\xc8\x01\x12#\n" +
	"\x1eTRACE_EVENT_REASON_MISS_SUBNET\x10\xc9\x01\x12&\n" +
	"!TRACE_EVENT_REASON_MISS_FIB_TABLE\x10\xca\x01\x12&\n" +
	"!TRACE_EVENT_REASON_MISS_FIB_ROUTE\x10\xcb\x01\x12 \n" +
	"\x1bTRACE_EVENT_REASON_MISS_ARP\x10\xcc\x01\x12 \n" +
	"\x1bTRACE_EVENT_REASON_MISS_FDB\x10\xcd\x01\x12$\n" +
	"\x1fTRACE_EVENT_REASON_MISS_SERVICE\x10\xce\x01\x12$\n" +
	"\x1fTRACE_EVENT_REASON_MISS_BACKEND\x10\xcf\x01\x12&\n" +
	"!TRACE_EVENT_REASON_MISS_CONNTRACK\x10\xd0\x01\x12&\n" +
	"!TRACE_EVENT_REASON_MISS_TGW_TABLE\x10\xd1\x01\x12&\n" +
	"!TRACE_EVENT_REASON_MISS_TGW_ROUTE\x10\xd2\x01\x12'\n" +
	"\"TRACE_EVENT_REASON_POLICY_ACL_PASS\x10\xac\x02\x12'\n" +
	"\"TRACE_EVENT_REASON_POLICY_ACL_DROP\x10\xad\x02\x12&\n" +
	"!TRACE_EVENT_REASON_POLICY_SG_PASS\x10\xae\x02\x12&\n" +
	"!TRACE_EVENT_REASON_POLICY_SG_DROP\x10\xaf\x02\x12*\n" +
	"%TRACE_EVENT_REASON_SERVICE_LOOKUP_HIT\x10\x90\x03\x120\n" +
	"+TRACE_EVENT_REASON_SERVICE_BACKEND_SELECTED\x10\x91\x03\x12$\n" +
	"\x1fTRACE_EVENT_REASON_DNAT_APPLIED\x10\x92\x03\x12$\n" +
	"\x1fTRACE_EVENT_REASON_SNAT_APPLIED\x10\x93\x03\x12&\n" +
	"!TRACE_EVENT_REASON_NAPT_ALLOCATED\x10\x94\x03\x12+\n" +
	"&TRACE_EVENT_REASON_REVERSE_NAT_APPLIED\x10\x95\x03\x12(\n" +
	"#TRACE_EVENT_REASON_REDIRECT_IFINDEX\x10\xf4\x03\x12&\n" +
	"!TRACE_EVENT_REASON_REDIRECT_VXLAN\x10\xf5\x03\x12#\n" +
	"\x1eTRACE_EVENT_REASON_PASS_KERNEL\x10\xf6\x03\x12!\n" +
	"\x1cTRACE_EVENT_REASON_DROP_SHOT\x10\xf7\x03\x12&\n" +
	"!TRACE_EVENT_REASON_DROP_BLACKHOLE\x10\xf8\x032\xb9\x03\n" +
	"\x05Debug\x12A\n" +
	"\n" +
	"WatchTrace\x12\x1b.debug.v1.WatchTraceRequest\x1a\x14.debug.v1.TraceEvent0\x01\x12N\n" +
	"\x10GetTraceSnapshot\x12!.debug.v1.GetTraceSnapshotRequest\x1a\x17.debug.v1.TraceSnapshot\x12J\n" +
	"\vInjectProbe\x12\x1c.debug.v1.InjectProbeRequest\x1a\x1d.debug.v1.InjectProbeResponse\x12A\n" +
	"\n" +
	"LearnTuple\x12\x1b.debug.v1.LearnTupleRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\vListBPFMaps\x12\x1c.debug.v1.ListBPFMapsRequest\x1a\x1d.debug.v1.ListBPFMapsResponse\x12B\n" +
	"\n" +
	"DumpBPFMap\x12\x1b.debug.v1.DumpBPFMapRequest\x1a\x15.debug.v1.BPFMapEntry0\x01B.Z,github.com/1outres/juneau/daemon/pkg/debugpbb\x06proto3"

var (
	file_pkg_debugpb_debug_proto_rawDescOnce sync.Once
	file_pkg_debugpb_debug_proto_rawDescData []byte
)

func file_pkg_debugpb_debug_proto_rawDescGZIP() []byte {
	file_pkg_debugpb_debug_proto_rawDescOnce.Do(func() {
		file_pkg_debugpb_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_debugpb_debug_proto_rawDesc), len(file_pkg_debugpb_debug_proto_rawDesc)))
	})
	return file_pkg_debugpb_debug_proto_rawDescData
}

var file_pkg_debugpb_debug_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_pkg_debugpb_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_debugpb_debug_proto_goTypes = []any{
	(InjectProbeStrategy)(0),        // 0: debug.v1.InjectProbeStrategy
	(TraceDirection)(0),             // 1: debug.v1.TraceDirection
	(TupleScope)(0),                 // 2: debug.v1.TupleScope
	(TraceProtocol)(0),              // 3: debug.v1.TraceProtocol
	(TraceHook)(0),                  // 4: debug.v1.TraceHook
	(TraceVerdict)(0),               // 5: debug.v1.TraceVerdict
	(TraceEventReason)(0),           // 6: debug.v1.TraceEventReason
	(*WatchTraceRequest)(nil),       // 7: debug.v1.WatchTraceRequest
	(*GetTraceSnapshotRequest)(nil), // 8: debug.v1.GetTraceSnapshotRequest
	(*TraceSnapshot)(nil),           // 9: debug.v1.TraceSnapshot
	(*InjectProbeRequest)(nil),      // 10: debug.v1.InjectProbeRequest
	(*InjectProbeResponse)(nil),     // 11: debug.v1.InjectProbeResponse
	(*LearnTupleRequest)(nil),       // 12: debug.v1.LearnTupleRequest
	(*TraceTuple)(nil),              // 13: debug.v1.TraceTuple
	(*TraceEvent)(nil),              // 14: debug.v1.TraceEvent
	(*BPFMapField)(nil),             // 15: debug.v1.BPFMapField
	(*BPFMapFieldSchema)(nil),       // 16: debug.v1.BPFMapFieldSchema
	(*BPFMapSchema)(nil),            // 17: debug.v1.BPFMapSchema
	(*ListBPFMapsRequest)(nil),      // 18: debug.v1.ListBPFMapsRequest
	(*ListBPFMapsResponse)(nil),     // 19: debug.v1.ListBPFMapsResponse
	(*DumpBPFMapRequest)(nil),       // 20: debug.v1.DumpBPFMapRequest
	(*BPFMapEntry)(nil),             // 21: debug.v1.BPFMapEntry
	(*emptypb.Empty)(nil),           // 22: google.protobuf.Empty
}
var file_pkg_debugpb_debug_proto_depIdxs = []int32{
	13, // 0: debug.v1.TraceSnapshot.tuples:type_name -> debug.v1.TraceTuple
	14, // 1: debug.v1.TraceSnapshot.recent_events:type_name -> debug.v1.TraceEvent
	0,  // 2: debug.v1.InjectProbeRequest.strategy:type_name -> debug.v1.InjectProbeStrategy
	13, // 3: debug.v1.InjectProbeRequest.tuple:type_name -> debug.v1.TraceTuple
	13, // 4: debug.v1.LearnTupleRequest.tuple:type_name -> debug.v1.TraceTuple
	2,  // 5: debug.v1.TraceTuple.scope:type_name -> debug.v1.TupleScope
	3,  // 6: debug.v1.TraceTuple.protocol:type_name -> debug.v1.TraceProtocol
	1,  // 7: debug.v1.TraceTuple.direction:type_name -> debug.v1.TraceDirection
	6,  // 8: debug.v1.TraceEvent.reason:type_name -> debug.v1.TraceEventReason
	4,  // 9: debug.v1.TraceEvent.hook:type_name -> debug.v1.TraceHook
	3,  // 10: debug.v1.TraceEvent.protocol:type_name -> debug.v1.TraceProtocol
	5,  // 11: debug.v1.TraceEvent.verdict:type_name -> debug.v1.TraceVerdict
	2,  // 12: debug.v1.TraceEvent.scope:type_name -> debug.v1.TupleScope
	1,  // 13: debug.v1.TraceEvent.direction:type_name -> debug.v1.TraceDirection
	16, // 14: debug.v1.BPFMapSchema.key_schema:type_name -> debug.v1.BPFMapFieldSchema
	16, // 15: debug.v1.BPFMapSchema.value_schema:type_name -> debug.v1.BPFMapFieldSchema
	16, // 16: debug.v1.BPFMapSchema.inner_key_schema:type_name -> debug.v1.BPFMapFieldSchema
	16, // 17: debug.v1.BPFMapSchema.inner_value_schema:type_name -> debug.v1.BPFMapFieldSchema
	17, // 18: debug.v1.ListBPFMapsResponse.maps:type_name -> debug.v1.BPFMapSchema
	15, // 19: debug.v1.DumpBPFMapRequest.key_filter:type_name -> debug.v1.BPFMapField
	15, // 20: debug.v1.DumpBPFMapRequest.inner_key:type_name -> debug.v1.BPFMapField
	15, // 21: debug.v1.BPFMapEntry.key:type_name -> debug.v1.BPFMapField
	15, // 22: debug.v1.BPFMapEntry.value:type_name -> debug.v1.BPFMapField
	7,  // 23: debug.v1.Debug.WatchTrace:input_type -> debug.v1.WatchTraceRequest
	8,  // 24: debug.v1.Debug.GetTraceSnapshot:input_type -> debug.v1.GetTraceSnapshotRequest
	10, // 25: debug.v1.Debug.InjectProbe:input_type -> debug.v1.InjectProbeRequest
	12, // 26: debug.v1.Debug.LearnTuple:input_type -> debug.v1.LearnTupleRequest
	18, // 27: debug.v1.Debug.ListBPFMaps:input_type -> debug.v1.ListBPFMapsRequest
	20, // 28: debug.v1.Debug.DumpBPFMap:input_type -> debug.v1.DumpBPFMapRequest
	14, // 29: debug.v1.Debug.WatchTrace:output_type -> debug.v1.TraceEvent
	9,  // 30: debug.v1.Debug.GetTraceSnapshot:output_type -> debug.v1.TraceSnapshot
	11, // 31: debug.v1.Debug.InjectProbe:output_type -> debug.v1.InjectProbeResponse
	22, // 32: debug.v1.Debug.LearnTuple:output_type -> google.protobuf.Empty
	19, // 33: debug.v1.Debug.ListBPFMaps:output_type -> debug.v1.ListBPFMapsResponse
	21, // 34: debug.v1.Debug.DumpBPFMap:output_type -> debug.v1.BPFMapEntry
	29, // [29:35] is the sub-list for method output_type
	23, // [23:29] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pkg_debugpb_debug_proto_init() }
func file_pkg_debugpb_debug_proto_init() {
	if File_pkg_debugpb_debug_proto != nil {
		return
	}
	file_pkg_debugpb_debug_proto_msgTypes[8].OneofWrappers = []any{
		(*BPFMapField_U64)(nil),
		(*BPFMapField_Ipv4)(nil),
		(*BPFMapField_Mac)(nil),
		(*BPFMapField_Label)(nil),
		(*BPFMapField_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_debugpb_debug_proto_rawDesc), len(file_pkg_debugpb_debug_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_debugpb_debug_proto_goTypes,
		DependencyIndexes: file_pkg_debugpb_debug_proto_depIdxs,
		EnumInfos:         file_pkg_debugpb_debug_proto_enumTypes,
		MessageInfos:      file_pkg_debugpb_debug_proto_msgTypes,
	}.Build()
	File_pkg_debugpb_debug_proto = out.File
	file_pkg_debugpb_debug_proto_goTypes = nil
	file_pkg_debugpb_debug_proto_depIdxs = nil
}
