// debug.proto carries the operational debug API kubectl-juneau
// uses to drive a trace session: it streams ringbuf events from one
// daemon, exchanges learned tuples between daemons, and lets kubectl
// inject probes when active probing is requested.
//
// The service is intentionally distinct from CNI (cni.proto) — CNI
// is wired into the kubelet boot sequence and must stay frozen while
// the trace API is operator-facing and may evolve more frequently.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: pkg/debugpb/debug.proto

package debugpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Debug_WatchTrace_FullMethodName       = "/debug.v1.Debug/WatchTrace"
	Debug_GetTraceSnapshot_FullMethodName = "/debug.v1.Debug/GetTraceSnapshot"
	Debug_InjectProbe_FullMethodName      = "/debug.v1.Debug/InjectProbe"
	Debug_LearnTuple_FullMethodName       = "/debug.v1.Debug/LearnTuple"
)

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DebugClient interface {
	// WatchTrace streams every trace event observed on this node
	// belonging to one of the requested trace IDs. The stream stays
	// open until the client cancels or the daemon shuts down.
	//
	// Empty trace_ids mean "every trace event". Daemons cap this to
	// protect themselves; kubectl always supplies a concrete list.
	WatchTrace(ctx context.Context, in *WatchTraceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error)
	// GetTraceSnapshot returns the daemon's view of one session: which
	// tuples are programmed, when the daemon last emitted an event,
	// and a bounded backlog of recent events. Used by kubectl when
	// the timeline is rendered after the live stream begins.
	GetTraceSnapshot(ctx context.Context, in *GetTraceSnapshotRequest, opts ...grpc.CallOption) (*TraceSnapshot, error)
	// InjectProbe asks the daemon to send a synthetic packet matching
	// an initial tuple of the requested session. Returns immediately
	// after the packet is queued; observed events flow back over
	// WatchTrace.
	InjectProbe(ctx context.Context, in *InjectProbeRequest, opts ...grpc.CallOption) (*InjectProbeResponse, error)
	// LearnTuple installs a translated tuple on this node so a
	// post-NAT continuation of an existing session can be matched
	// here. Used by kubectl to mirror tuples it receives from one
	// daemon over to the daemons whose dataplane may also see the
	// packet.
	LearnTuple(ctx context.Context, in *LearnTupleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type debugClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugClient(cc grpc.ClientConnInterface) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) WatchTrace(ctx context.Context, in *WatchTraceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Debug_ServiceDesc.Streams[0], Debug_WatchTrace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTraceRequest, TraceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Debug_WatchTraceClient = grpc.ServerStreamingClient[TraceEvent]

func (c *debugClient) GetTraceSnapshot(ctx context.Context, in *GetTraceSnapshotRequest, opts ...grpc.CallOption) (*TraceSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceSnapshot)
	err := c.cc.Invoke(ctx, Debug_GetTraceSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) InjectProbe(ctx context.Context, in *InjectProbeRequest, opts ...grpc.CallOption) (*InjectProbeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectProbeResponse)
	err := c.cc.Invoke(ctx, Debug_InjectProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) LearnTuple(ctx context.Context, in *LearnTupleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Debug_LearnTuple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebugServer is the server API for Debug service.
// All implementations must embed UnimplementedDebugServer
// for forward compatibility.
type DebugServer interface {
	// WatchTrace streams every trace event observed on this node
	// belonging to one of the requested trace IDs. The stream stays
	// open until the client cancels or the daemon shuts down.
	//
	// Empty trace_ids mean "every trace event". Daemons cap this to
	// protect themselves; kubectl always supplies a concrete list.
	WatchTrace(*WatchTraceRequest, grpc.ServerStreamingServer[TraceEvent]) error
	// GetTraceSnapshot returns the daemon's view of one session: which
	// tuples are programmed, when the daemon last emitted an event,
	// and a bounded backlog of recent events. Used by kubectl when
	// the timeline is rendered after the live stream begins.
	GetTraceSnapshot(context.Context, *GetTraceSnapshotRequest) (*TraceSnapshot, error)
	// InjectProbe asks the daemon to send a synthetic packet matching
	// an initial tuple of the requested session. Returns immediately
	// after the packet is queued; observed events flow back over
	// WatchTrace.
	InjectProbe(context.Context, *InjectProbeRequest) (*InjectProbeResponse, error)
	// LearnTuple installs a translated tuple on this node so a
	// post-NAT continuation of an existing session can be matched
	// here. Used by kubectl to mirror tuples it receives from one
	// daemon over to the daemons whose dataplane may also see the
	// packet.
	LearnTuple(context.Context, *LearnTupleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDebugServer()
}

// UnimplementedDebugServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDebugServer struct{}

func (UnimplementedDebugServer) WatchTrace(*WatchTraceRequest, grpc.ServerStreamingServer[TraceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchTrace not implemented")
}
func (UnimplementedDebugServer) GetTraceSnapshot(context.Context, *GetTraceSnapshotRequest) (*TraceSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraceSnapshot not implemented")
}
func (UnimplementedDebugServer) InjectProbe(context.Context, *InjectProbeRequest) (*InjectProbeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectProbe not implemented")
}
func (UnimplementedDebugServer) LearnTuple(context.Context, *LearnTupleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LearnTuple not implemented")
}
func (UnimplementedDebugServer) mustEmbedUnimplementedDebugServer() {}
func (UnimplementedDebugServer) testEmbeddedByValue()               {}

// UnsafeDebugServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DebugServer will
// result in compilation errors.
type UnsafeDebugServer interface {
	mustEmbedUnimplementedDebugServer()
}

func RegisterDebugServer(s grpc.ServiceRegistrar, srv DebugServer) {
	// If the following call pancis, it indicates UnimplementedDebugServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Debug_ServiceDesc, srv)
}

func _Debug_WatchTrace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTraceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DebugServer).WatchTrace(m, &grpc.GenericServerStream[WatchTraceRequest, TraceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Debug_WatchTraceServer = grpc.ServerStreamingServer[TraceEvent]

func _Debug_GetTraceSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).GetTraceSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Debug_GetTraceSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).GetTraceSnapshot(ctx, req.(*GetTraceSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_InjectProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).InjectProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Debug_InjectProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).InjectProbe(ctx, req.(*InjectProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_LearnTuple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LearnTupleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).LearnTuple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Debug_LearnTuple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).LearnTuple(ctx, req.(*LearnTupleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Debug_ServiceDesc is the grpc.ServiceDesc for Debug service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Debug_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "debug.v1.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTraceSnapshot",
			Handler:    _Debug_GetTraceSnapshot_Handler,
		},
		{
			MethodName: "InjectProbe",
			Handler:    _Debug_InjectProbe_Handler,
		},
		{
			MethodName: "LearnTuple",
			Handler:    _Debug_LearnTuple_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTrace",
			Handler:       _Debug_WatchTrace_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/debugpb/debug.proto",
}
