# Grants permissions to manage NetworkInterfaceAttachment resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: networkinterfaceattachment-editor-role
rules:
- apiGroups:
  - juneau.loutres.me
  resources:
  - networkinterfaceattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
