---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juneau.loutres.me
  resources:
  - addresspools
  - bgpadvertisements
  - bgppeers
  - elasticipattachments
  - elasticips
  - externalnetworks
  - ipleases
  - networkendpoints
  - networkinterfaces
  - routetables
  - subnets
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juneau.loutres.me
  resources:
  - addresspools/finalizers
  - bgpadvertisements/finalizers
  - bgppeers/finalizers
  - elasticipattachments/finalizers
  - elasticips/finalizers
  - externalnetworks/finalizers
  - ipleases/finalizers
  - networkendpoints/finalizers
  - networkinterfaces/finalizers
  - routetables/finalizers
  - subnets/finalizers
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - juneau.loutres.me
  resources:
  - addresspools/status
  - bgpadvertisements/status
  - bgppeers/status
  - elasticipattachments/status
  - elasticips/status
  - externalnetworks/status
  - ipleases/status
  - networkendpoints/status
  - networkinterfaces/status
  - routetables/status
  - subnets/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - juneau.loutres.me
  resources:
  - bgpnodestates
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
