---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juneau.loutres.me
  resources:
  - ipleases
  - networkendpoints
  - networkinterfaces
  - subnets
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juneau.loutres.me
  resources:
  - ipleases/finalizers
  - networkendpoints/finalizers
  - networkinterfaces/finalizers
  - subnets/finalizers
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - juneau.loutres.me
  resources:
  - ipleases/status
  - networkendpoints/status
  - networkinterfaces/status
  - subnets/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
