---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - juneau.loutres.me
  resources:
  - addresses
  - subnets
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juneau.loutres.me
  resources:
  - addresses/finalizers
  - subnets/finalizers
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - juneau.loutres.me
  resources:
  - addresses/status
  - subnets/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
