# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over juneau.loutres.me tracesessions.
# This role is intended for cluster administrators (and operators running
# `kubectl juneau trace`) who need full control over these resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: tracesession-admin-role
rules:
- apiGroups:
  - juneau.loutres.me
  resources:
  - tracesessions
  verbs:
  - '*'
- apiGroups:
  - juneau.loutres.me
  resources:
  - tracesessions/status
  verbs:
  - get
