/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/1outres/juneau/controller/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AddressLister helps list Addresses.
// All objects returned here must be treated as read-only.
type AddressLister interface {
	// List lists all Addresses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Address, err error)
	// Addresses returns an object that can list and get Addresses.
	Addresses(namespace string) AddressNamespaceLister
	AddressListerExpansion
}

// addressLister implements the AddressLister interface.
type addressLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Address]
}

// NewAddressLister returns a new AddressLister.
func NewAddressLister(indexer cache.Indexer) AddressLister {
	return &addressLister{listers.New[*apiv1alpha1.Address](indexer, apiv1alpha1.Resource("address"))}
}

// Addresses returns an object that can list and get Addresses.
func (s *addressLister) Addresses(namespace string) AddressNamespaceLister {
	return addressNamespaceLister{listers.NewNamespaced[*apiv1alpha1.Address](s.ResourceIndexer, namespace)}
}

// AddressNamespaceLister helps list and get Addresses.
// All objects returned here must be treated as read-only.
type AddressNamespaceLister interface {
	// List lists all Addresses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Address, err error)
	// Get retrieves the Address from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.Address, error)
	AddressNamespaceListerExpansion
}

// addressNamespaceLister implements the AddressNamespaceLister
// interface.
type addressNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Address]
}
