namespace: system

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - rolebinding.yaml
  - job.yaml
  - cronjob.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhookcertjob
  newName: example.com/webhookcertjob
  newTag: v0.0.1
