apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  labels:
    app.kubernetes.io/name: webhook-cert-job
    app.kubernetes.io/part-of: juneau
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
