// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/juneau.v1.proto

package juneaupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CNIIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerId   string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	IfName        string                 `protobuf:"bytes,5,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	PodUid        string                 `protobuf:"bytes,6,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CNIIdentity) Reset() {
	*x = CNIIdentity{}
	mi := &file_proto_juneau_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNIIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIIdentity) ProtoMessage() {}

func (x *CNIIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juneau_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIIdentity.ProtoReflect.Descriptor instead.
func (*CNIIdentity) Descriptor() ([]byte, []int) {
	return file_proto_juneau_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CNIIdentity) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CNIIdentity) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *CNIIdentity) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CNIIdentity) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CNIIdentity) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *CNIIdentity) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

type AllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *CNIIdentity           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_proto_juneau_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juneau_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_proto_juneau_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateRequest) GetId() *CNIIdentity {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AllocateRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type AllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	IpAssignment  *IPAssignment          `protobuf:"bytes,2,opt,name=ip_assignment,json=ipAssignment,proto3" json:"ip_assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_proto_juneau_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juneau_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_proto_juneau_v1_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AllocateResponse) GetIpAssignment() *IPAssignment {
	if x != nil {
		return x.IpAssignment
	}
	return nil
}

type IPAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          *IPConfig              `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAssignment) Reset() {
	*x = IPAssignment{}
	mi := &file_proto_juneau_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAssignment) ProtoMessage() {}

func (x *IPAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juneau_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAssignment.ProtoReflect.Descriptor instead.
func (*IPAssignment) Descriptor() ([]byte, []int) {
	return file_proto_juneau_v1_proto_rawDescGZIP(), []int{3}
}

func (x *IPAssignment) GetIpv4() *IPConfig {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_juneau_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juneau_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_juneau_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressCidr   string                 `protobuf:"bytes,1,opt,name=address_cidr,json=addressCidr,proto3" json:"address_cidr,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPConfig) Reset() {
	*x = IPConfig{}
	mi := &file_proto_juneau_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPConfig) ProtoMessage() {}

func (x *IPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juneau_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPConfig.ProtoReflect.Descriptor instead.
func (*IPConfig) Descriptor() ([]byte, []int) {
	return file_proto_juneau_v1_proto_rawDescGZIP(), []int{5}
}

func (x *IPConfig) GetAddressCidr() string {
	if x != nil {
		return x.AddressCidr
	}
	return ""
}

func (x *IPConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

var File_proto_juneau_v1_proto protoreflect.FileDescriptor

const file_proto_juneau_v1_proto_rawDesc = "" +
	"\n" +
	"\x15proto/juneau.v1.proto\x12\aecho.v1\"\xbf\x01\n" +
	"\vCNIIdentity\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12\x17\n" +
	"\aif_name\x18\x05 \x01(\tR\x06ifName\x12\x17\n" +
	"\apod_uid\x18\x06 \x01(\tR\x06podUid\"X\n" +
	"\x0fAllocateRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\v2\x14.echo.v1.CNIIdentityR\x02id\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\"t\n" +
	"\x10AllocateResponse\x12$\n" +
	"\x05error\x18\x01 \x01(\v2\x0e.echo.v1.ErrorR\x05error\x12:\n" +
	"\rip_assignment\x18\x02 \x01(\v2\x15.echo.v1.IPAssignmentR\fipAssignment\"5\n" +
	"\fIPAssignment\x12%\n" +
	"\x04ipv4\x18\x01 \x01(\v2\x11.echo.v1.IPConfigR\x04ipv4\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\bIPConfig\x12!\n" +
	"\faddress_cidr\x18\x01 \x01(\tR\vaddressCidr\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway2G\n" +
	"\x04IPAM\x12?\n" +
	"\bAllocate\x12\x18.echo.v1.AllocateRequest\x1a\x19.echo.v1.AllocateResponseB\x17Z\x15pkg/juneaupb;juneaupbb\x06proto3"

var (
	file_proto_juneau_v1_proto_rawDescOnce sync.Once
	file_proto_juneau_v1_proto_rawDescData []byte
)

func file_proto_juneau_v1_proto_rawDescGZIP() []byte {
	file_proto_juneau_v1_proto_rawDescOnce.Do(func() {
		file_proto_juneau_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_juneau_v1_proto_rawDesc), len(file_proto_juneau_v1_proto_rawDesc)))
	})
	return file_proto_juneau_v1_proto_rawDescData
}

var file_proto_juneau_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_juneau_v1_proto_goTypes = []any{
	(*CNIIdentity)(nil),      // 0: echo.v1.CNIIdentity
	(*AllocateRequest)(nil),  // 1: echo.v1.AllocateRequest
	(*AllocateResponse)(nil), // 2: echo.v1.AllocateResponse
	(*IPAssignment)(nil),     // 3: echo.v1.IPAssignment
	(*Error)(nil),            // 4: echo.v1.Error
	(*IPConfig)(nil),         // 5: echo.v1.IPConfig
}
var file_proto_juneau_v1_proto_depIdxs = []int32{
	0, // 0: echo.v1.AllocateRequest.id:type_name -> echo.v1.CNIIdentity
	4, // 1: echo.v1.AllocateResponse.error:type_name -> echo.v1.Error
	3, // 2: echo.v1.AllocateResponse.ip_assignment:type_name -> echo.v1.IPAssignment
	5, // 3: echo.v1.IPAssignment.ipv4:type_name -> echo.v1.IPConfig
	1, // 4: echo.v1.IPAM.Allocate:input_type -> echo.v1.AllocateRequest
	2, // 5: echo.v1.IPAM.Allocate:output_type -> echo.v1.AllocateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_juneau_v1_proto_init() }
func file_proto_juneau_v1_proto_init() {
	if File_proto_juneau_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_juneau_v1_proto_rawDesc), len(file_proto_juneau_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_juneau_v1_proto_goTypes,
		DependencyIndexes: file_proto_juneau_v1_proto_depIdxs,
		MessageInfos:      file_proto_juneau_v1_proto_msgTypes,
	}.Build()
	File_proto_juneau_v1_proto = out.File
	file_proto_juneau_v1_proto_goTypes = nil
	file_proto_juneau_v1_proto_depIdxs = nil
}
