apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../controller/config/default
  - ../daemon/config/default
  - ../bgp-speaker/config/default

images:
  - name: example.com/controller
    newName: ghcr.io/1outres/juneau/controller
  - name: example.com/webhookcertjob
    newName: ghcr.io/1outres/juneau/webhookcertjob
  - name: daemon
    newName: ghcr.io/1outres/juneau/daemon
  - name: bgp-speaker
    newName: ghcr.io/1outres/juneau/bgp-speaker
