// Package packetplane is the userspace half of the virtual service
// dataplane. It owns the TAP device the BPF classifier redirects to,
// reads frames off the TAP, reconstructs tenant context from the BPF
// flow map, dispatches to handlers, and emits responses straight to
// the Pod's host-side veth via AF_PACKET (bypassing the host routing
// table, which has no native vpc_id dimension).
package packetplane

import (
	"errors"
	"fmt"
	"os"

	"github.com/vishvananda/netlink"
	"go.uber.org/zap"
)

// TAP wraps the lifecycle of the daemon's virtual-service TAP device.
//
// Frames written to the BPF redirect target (this TAP's ifindex)
// surface on Fd as readable Ethernet frames; conversely, packets the
// daemon writes to Fd are injected into the kernel as if they came
// from the TAP, which we deliberately do *not* use for response
// delivery (the host routing table cannot resolve overlapping Pod
// IPs across VPCs). Responses go via AF_PACKET on the Pod's
// host-side veth — see Sender.
//
// The TAP is created with IFF_NO_PI so reads/writes are raw Ethernet
// frames with no 4-byte tun_pi prefix, matching what BPF redirect
// produces.
type TAP struct {
	name    string
	link    netlink.Link
	fd      *os.File // /dev/net/tun handle keeping the device alive
	ifindex int
}

// TAPName is the canonical name of the daemon's virtual-service TAP
// device. Constant so the BPF classifier and the userspace reader
// agree without extra plumbing.
const TAPName = "juneau-svc0"

// CreateTAP brings up a TAP device named TAPName, configures it with
// the supplied MTU, and returns a handle whose Ifindex callers must
// program into virtual_service_map so BPF can redirect to it.
//
// Idempotency: if a device with the same name already exists (e.g. a
// stale interface from a previous daemon run), CreateTAP deletes it
// first and re-creates it. The TAP is owned by the daemon process and
// vanishes when the process exits.
//
// MTU: callers should pass the host's MTU minus the VXLAN overhead
// (50 bytes for IPv4) so DNS responses generated by the resolver fit
// without fragmentation when carried over the underlay. 1450 is a safe
// default for the standard 1500 host MTU.
func CreateTAP(mtu int) (*TAP, error) {
	if existing, err := netlink.LinkByName(TAPName); err == nil {
		if delErr := netlink.LinkDel(existing); delErr != nil {
			return nil, fmt.Errorf("delete stale %s: %w", TAPName, delErr)
		}
	}

	tt := &netlink.Tuntap{
		LinkAttrs:  netlink.LinkAttrs{Name: TAPName, MTU: mtu},
		Mode:       netlink.TUNTAP_MODE_TAP,
		// IFF_NO_PI: raw Ethernet frames, no 4-byte tun_pi prefix.
		// IFF_VNET_HDR is intentionally NOT set — we don't speak the
		// virtio_net header BPF wouldn't produce.
		Flags:      netlink.TUNTAP_NO_PI,
		Queues:     1,
		NonPersist: true,
	}
	if err := netlink.LinkAdd(tt); err != nil {
		return nil, fmt.Errorf("create %s: %w", TAPName, err)
	}

	link, err := netlink.LinkByName(TAPName)
	if err != nil {
		return nil, fmt.Errorf("look up %s after create: %w", TAPName, err)
	}
	if err := netlink.LinkSetUp(link); err != nil {
		return nil, fmt.Errorf("set %s up: %w", TAPName, err)
	}

	if len(tt.Fds) == 0 {
		return nil, errors.New("netlink.LinkAdd returned no TAP fds")
	}

	zap.S().Infof("packetplane: created TAP %s (ifindex=%d, mtu=%d)", TAPName, link.Attrs().Index, mtu)

	return &TAP{
		name:    TAPName,
		link:    link,
		fd:      tt.Fds[0],
		ifindex: link.Attrs().Index,
	}, nil
}

// Ifindex returns the kernel ifindex assigned to the TAP. This is the
// number BPF programs use as the bpf_redirect() target.
func (t *TAP) Ifindex() int { return t.ifindex }

// Name returns the netdev name of the TAP.
func (t *TAP) Name() string { return t.name }

// Fd returns the *os.File backing the TAP. Reads return raw Ethernet
// frames the BPF program redirected to this device. The file is owned
// by the TAP — close it via Close, not directly.
func (t *TAP) Fd() *os.File { return t.fd }

// Close removes the TAP from the kernel and releases the backing fd.
// Safe to call once; subsequent calls are no-ops.
func (t *TAP) Close() error {
	if t.fd == nil {
		return nil
	}
	closeErr := t.fd.Close()
	t.fd = nil

	delErr := netlink.LinkDel(t.link)
	if delErr != nil && !errors.Is(delErr, os.ErrNotExist) {
		// Some kernels return "no such device" when the device has
		// already been auto-removed (e.g. NonPersist + last fd
		// closed); swallow that, surface anything else.
		if _, ok := delErr.(netlink.LinkNotFoundError); !ok {
			return fmt.Errorf("delete TAP %s: %w", t.name, delErr)
		}
	}
	return closeErr
}
